# -*- coding: utf-8 -*-
"""Oral Exam, part 4 — the coverage sweep, plus the Scenarios sub-section.

PART A, APPENDS: a topic-by-topic pass over the guide found 43 headings that
had a definition item in the app but no QUESTION. Recall is not application,
and the examiner only ever asks the second one. Those are answered here as
questions APPENDED to the existing bank for that Area — appended, never
inserted, so every existing index (and the progress keyed to it) is untouched.

PART B, SCENARIOS: the guide is organised by Task because the ACS is, but a
DPE does not run it that way. They take ONE situation and walk it across
Tasks: your nav log becomes weather, which becomes performance, which becomes
airspace, which becomes a diversion. These four banks are that — a single
scenario per bank, developing question by question.

PPL scope throughout: no IMC, no partial panel, no approaches.
"""

A = '➔'

# ===================================================================
# PART A — APPENDS, BY AREA
# ===================================================================

# --- I.A Pilot Qualifications -> OralPrereq ------------------------
APP_PREREQ = [
 ("Name the eligibility requirements for a private pilot certificate.",
  ["Be 17; read, speak, write and understand English; hold a medical or BasicMed; hold the training endorsements; meet the experience; pass the knowledge and practical tests.",
   "Be 18; hold a student certificate; log 40 hours; pass the knowledge and practical tests.",
   "Be 17; hold a third-class medical; log 35 hours; pass the practical test."],
  "61.103, and it is a LIST — the examiner is counting. Two items people drop: the English requirement is read, speak, WRITE and understand, all four; and 61.103(j) requires you to already hold a student, sport or recreational certificate. 18 belongs to the commercial certificate and 35 hours belongs to a Part 141 course."),
 ("What keeps you legal to act as PIC at all, as opposed to carrying passengers?",
  ["A flight review within the preceding 24 calendar months — 1 hour of ground and 1 hour of flight.",
   "Three takeoffs and landings within the preceding 90 days.",
   "A current medical certificate alone."],
  "61.56 is the PIC-at-all rule; 61.57 is the extra layer for carrying passengers. They are different clocks answering different questions, and merging them is the standard error. A new certificate or rating resets the flight review, and the review is not a test — there is no pass or fail, only an endorsement or no endorsement."),
 ("You want to carry a passenger at 21:00, well after dark. What do you need beyond day currency?",
  ["3 takeoffs and landings to a FULL STOP in the preceding 90 days, flown between 1 hour after sunset and 1 hour before sunrise.",
   "3 takeoffs and landings in the preceding 90 days, touch-and-go acceptable, any time of day.",
   "A night rating endorsement from an instructor."],
  "Full stop, and inside the 1-after-to-1-before window — both conditions. Keep the three night definitions apart: position lights run sunset to sunrise, LOGGING night time uses civil twilight, and PASSENGER night currency uses the 1-hour window. There is no such thing as a US night rating."),
 ("A friend offers to pay for all the fuel on a flight you are both taking. May you accept?",
  ["No — you may never pay LESS than your pro rata share of the operating expenses.",
   "Yes, provided the flight is not for business purposes.",
   "Yes, since fuel is an operating expense and may be shared in any proportion."],
  "61.113(c) lets you SHARE fuel, oil, airport expenditures and rental fees — and only those four — but your share can never fall below equal. Two people means you pay at least half. The rule exists to stop a private pilot quietly running a charter operation, so the FAA reads it strictly and so should you."),
 ("Which of these may a private pilot legally do?",
  ["Demonstrate an aircraft in flight to a buyer, if they are an aircraft salesman with at least 200 hours logged.",
   "Fly skydivers for a jump operation, provided they are not paid personally.",
   "Give sightseeing flights for a charity, charging passengers directly."],
  "The salesman privilege is in 61.113(f) and the 200 hours is the part people forget. The charity privilege in 61.113(d) is real but tightly conditioned and it is not the pilot charging passengers. Dropping jumpers for hire is a commercial operation. Ask who is paying and for what, and most of these answer themselves."),
 ("What personal documents must be with you for a flight?",
  ["Pilot certificate, medical certificate or BasicMed, and a government-issued photo and signature ID.",
   "Pilot certificate, medical certificate, logbook and the aircraft's ARROW documents.",
   "Pilot certificate and logbook; the medical may be kept on file at the school."],
  "61.3 wants the certificate and the medical; 61.3(a)(2) adds the photo ID. Your LOGBOOK is not a carriage item for a private pilot — 61.51(i) makes you present it on reasonable request, which is a different duty. The FCC radiotelephone permit joins the list only for flights outside the US."),
 ("You hold BasicMed. What are the aircraft limits?",
  ["Not more than 7 occupants, 12,500 pounds maximum certificated takeoff weight, and not more than 6 passengers.",
   "Not more than 6 occupants, 6,000 pounds, and not more than 5 passengers.",
   "Not more than 4 occupants and 4,000 pounds, with no passenger limit."],
  "The 2024 reauthorisation raised all three. 6 occupants, 6,000 pounds and 5 passengers are the ORIGINAL 2017 figures — they are still printed in a great deal of study material, including some school guides, which is exactly what makes them the distractor. Also 18,000 MSL, 250 KIAS, domestic, and not for hire."),
 ("Under BasicMed, who may perform the medical examination?",
  ["Any State-licensed physician — including an Aviation Medical Examiner, who is also one.",
   "Only an Aviation Medical Examiner designated by the FAA.",
   "Only a physician who has completed the FAA's BasicMed course themselves."],
  "No FAA designation is required, and that is the whole point of BasicMed. But an AME is a State-licensed physician too and may choose to perform one — so being seen by your usual AME does not invalidate it. The exam is every 48 calendar months and the online course every 24. Two clocks."),
 ("When must the shoulder harness be worn, as opposed to just the seat belt?",
  ["Crew: for taxi, takeoff and landing. En route, crew keep the belt only.",
   "Everyone on board, for the entire flight.",
   "Passengers only, for takeoff and landing."],
  "91.107 is deliberately asymmetric. Passengers are belted for taxi, takeoff and landing. Required crewmembers wear belt AND shoulder harness for taxi, takeoff and landing, and keep the belt fastened for the whole flight while at their station. If the harness would stop you reaching a required control, that is the one exception."),
 ("You are 26 today and hold a third-class medical issued last month. How long is it good for?",
  ["60 calendar months — the age that counts is your age on the day of the EXAM.",
   "24 calendar months, since third-class medicals always last two years.",
   "12 calendar months for all privileges."],
  "Under 40 on the day of the exam gives 60 calendar months; 40 or over gives 24. The trap is the pilot who turns 40 during the period — the certificate does not shorten, because the clock was set at the exam. Note also that a third-class medical covers private privileges only; a first or second class DOWNGRADES to third-class duration for private flying."),
 ("What does 61.53 add to holding a valid medical certificate?",
  ["A duty on EVERY flight: you may not act as PIC with a known condition that would stop you meeting your medical's requirements.",
   "Nothing — a valid medical certificate is the complete authority to fly.",
   "A requirement to consult an AME before any flight when feeling unwell."],
  "The certificate says an examiner found you fit on ONE day. 61.53 makes it your job on every other day, and it grounds you with nothing stamped or revoked — you self-ground, and there is no paperwork. IMSAFE is how you actually run the check: Illness, Medication, Stress, Alcohol, Fatigue, Emotion and Eating."),
 ("What is the difference between being current and being proficient?",
  ["Current means you have met the FAA minimum and may legally go. Proficient means you can fly it well today.",
   "They are the same thing — currency is the FAA's measure of proficiency.",
   "Proficient is the legal standard; current is an instructor's opinion."],
  "The regulation is a floor written for every pilot in the country; it says nothing about you, this aeroplane, or this week. An examiner asks this to hear whether you know that being legal and being safe are two separate questions — and the honest follow-up is what YOUR personal minimums are, which they will ask next."),
]

# --- I.B Airworthiness -> OralInop ---------------------------------
APP_INOP = [
 ("Your aircraft is due a 100-hour and an annual on the same day. Can one cover the other?",
  ["An annual can be substituted for the 100-hour, but a 100-hour can NEVER be substituted for an annual.",
   "Either can substitute for the other, since Part 43 Appendix D is the same scope list.",
   "Neither may substitute; both must be performed separately."],
  "The scope list IS the same — Part 43 Appendix D for both — so it is not about what gets inspected. It is about WHO SIGNS: an annual needs an A&P with an Inspection Authorisation, a 100-hour needs only an A&P. The higher qualification can cover the lower; the lower cannot reach up."),
 ("The annual expired last week and the aircraft must go to the maintenance base. What is required?",
  ["A Special Flight Permit under 21.197 — and every AD that is DUE must be complied with first.",
   "Nothing — a ferry flight to an inspection facility is exempt.",
   "A logbook entry by any A&P stating the aircraft is safe for the flight."],
  "The AD half is what people leave out, and it is the half that matters: the FAA will let you fly an aeroplane that is out of inspection, but not one with a known unsafe condition unaddressed. The permit is for a specific purpose and route, and the aircraft must be capable of safe flight even though it does not currently meet the requirements."),
 ("You are involved in an occurrence that causes substantial damage to the aircraft. Whom do you notify, and when?",
  ["The NTSB, immediately — and a written report follows within 10 days.",
   "The FAA Flight Standards District Office, within 48 hours.",
   "The NTSB, in writing, within 7 days."],
  "49 CFR 830 — note the title, 49 not 14, and the NTSB not the FAA. Immediate notification, then Form 6120.1 within 10 days for an ACCIDENT. The 7-day written report belongs to an aircraft that is overdue and believed missing, which is a different trigger altogether."),
 ("What is the difference between an accident and an incident?",
  ["An accident involves death, serious injury or substantial damage; an incident affects or could affect safety without reaching that threshold.",
   "An accident involves the aircraft; an incident involves only persons.",
   "An accident is reported to the NTSB; an incident is reported to the FAA."],
  "The definitions are in 49 CFR 830.2, and the thresholds are what decide which reporting rule applies. Note what does NOT count as substantial damage: bent fairings, dented skin, ground damage to a propeller, or damage to flaps, brakes or wingtips alone. A prop strike is the classic argument, and the definition is worth reading."),
 ("The examiner asks you to prove the aircraft is airworthy. Where do you start and what is the standard?",
  ["In the maintenance records — and the standard is that it conforms to its type certificate AND is in condition for safe operation.",
   "With the ARROW documents in the aircraft, since those are the legal proof.",
   "With the last annual inspection sign-off, which covers everything else."],
  "Conformity plus condition. ARROW proves the aircraft is REGISTERED and CERTIFICATED, not that it is airworthy today. You want the Annual, the 100-hour if it applies, the transponder and altimeter checks, the ELT, and AD compliance — dates and tach times, out of the books, which is a SKILL element the examiner grades as a demonstration."),
 ("Who may perform preventive maintenance on the aircraft, and what must be recorded?",
  ["A certificated pilot on an aircraft they own or operate — recording the work, the date, and their name, signature and certificate number.",
   "Only an A&P mechanic, who records the work and signs the logbook.",
   "Any pilot, on any aircraft, with only a date and initials required."],
  "43.3(g) gives the privilege, Part 43 Appendix A(c) is the closed list of 31 jobs, and 43.9 sets the record. Three constraints people drop: you must OWN OR OPERATE it, the aircraft must not be run under Part 121, 129 or 135, and the entry goes in the AIRCRAFT records, not your flight logbook."),
]

# --- I.C Weather -> OralWxQ ----------------------------------------
APP_WX = [
 ("Which chart shows pressure systems, isobars, fronts and air-mass boundaries, and how often?",
  ["The Surface Analysis Chart, every 3 hours.",
   "The Radar Summary Chart, hourly.",
   "The Low-Level Significant Weather Chart, four times a day."],
  "Surface analysis is your synoptic picture — where the systems are and which way they are moving, which is the 'big picture' half of your guide's big-to-small method. Radar summary is hourly and shows PRECIPITATION, never cloud. Low-level significant weather is 0000, 0600, 1200 and 1800Z, surface to FL240."),
 ("What does the Radar Summary Chart show that a satellite picture does not — and what does it NOT show?",
  ["It shows precipitation type, intensity, coverage, movement and echo tops — but it does not show cloud.",
   "It shows cloud cover and tops, but not precipitation intensity.",
   "It shows both cloud and precipitation, which is why it replaces the satellite image."],
  "Radar sees water drops big enough to return an echo, so a sky full of cloud with no rain in it is a blank chart. That is the trap: a clear radar picture is not a clear sky, and it certainly is not a guarantee of VFR. Use it for where the weather is ACTIVE, and the significant weather chart for where it is merely bad."),
 ("You see a PIREP for moderate turbulence. What is the first thing you look at?",
  ["The aircraft TYPE that filed it — moderate in a 172 is not moderate in a 737.",
   "The time it was filed, since PIREPs older than 30 minutes are discarded.",
   "The altitude only; aircraft type is not reported in a PIREP."],
  "A PIREP is the only REAL-TIME report of turbulence, icing and cloud tops, and the aircraft type is what calibrates it. A heavy jet reporting light chop may be a rough ride for you. File them too — through FSS, en route ATC or the tower — because the next pilot is in the same position you were."),
 ("How often does ATIS update, and how often do AWOS and ASOS?",
  ["ATIS hourly, normally at 55 past, with specials as needed. AWOS and ASOS every minute.",
   "All three update hourly at 55 minutes past the hour.",
   "ATIS every minute; AWOS and ASOS hourly."],
  "The difference is that ATIS is a recorded human broadcast and the automated systems are sensors talking directly. Practically it means an AWOS can already be showing you the change that the ATIS will not carry for another 40 minutes — which is exactly the situation on a deteriorating afternoon."),
 ("What does the GFA tool give you that a text briefing does not?",
  ["A graphical picture on aviationweather.gov of observations and forecasts across the route, hour by hour.",
   "A legally binding forecast that replaces the TAF for flight planning.",
   "Radar imagery only, with no forecast component."],
  "It is a visualisation layer over the same data, and it is where the old area forecast went. It does not replace the METAR and TAF for the terminal ends, and it is not itself the regulatory product — but for seeing WHERE the weather is along a route rather than reading it station by station, it is the fastest tool you have."),
 ("Name the three stages of a thunderstorm and what defines each.",
  ["Cumulus — updraft only; Mature — begins when precipitation reaches the ground, both drafts running; Dissipating — downdraft throughout.",
   "Building, Peak, Collapsing — defined by cloud height alone.",
   "Cumulus, Mature, Dissipating — defined by lightning frequency."],
  "The DEFINITION of each stage is the point, not the name. Precipitation reaching the surface is what marks mature, and mature is where all the hazards peak because both drafts are running side by side — over 6,000 fpm up and over 2,500 down. The cumulus stage is updraft only and can still exceed 3,000 fpm."),
 ("How do clouds form? Name the three ingredients.",
  ["Adequate water vapour, condensation nuclei, and a means of cooling the air.",
   "High humidity, unstable air, and a lifting force.",
   "Saturated air, a temperature inversion, and surface heating."],
  "Vapour, nuclei, cooling. The middle one — smoke, dust, salt, small particles for the vapour to condense onto — is the one nobody says, and it is why the FAA asks. Note the answer for THUNDERSTORMS is a different list: sufficient water vapour, an unstable lapse rate, and a lifting force."),
 ("What do lenticular clouds tell you?",
  ["Strong winds and a mountain wave — the cloud stands still while the air rushes through it.",
   "That the air mass is stable and the flight will be smooth beneath them.",
   "That precipitation is imminent at the surface."],
  "They form at the crest of a standing wave, which is why they do not move — which is also the tell. A mountain wave needs wind above about 25 knots blowing roughly perpendicular to the ridge; the lenticular marks the crest and a ROTOR cloud beneath it marks the worst turbulence. Neither is a place to be in a 172."),
 ("What are the two ways fog forms, and which type belongs to each?",
  ["Cooling the air to its dew point — radiation, advection and upslope; or ADDING moisture until the dew point rises to the temperature — steam fog.",
   "Cooling only — all four types form by the air being cooled to its dew point.",
   "Adding moisture only — all fog requires evaporation from a surface."],
  "Three of the four are cooling processes; steam fog is the odd one out because the air is not cooled at all, it is loaded with moisture from warm water beneath it. That mechanism is also why steam fog comes with turbulence and icing — cold unstable air sitting over a warm surface."),
 ("Which is the ONE fog type that requires wind to form?",
  ["Advection fog — the wind has to carry the warm moist air over the cold surface.",
   "Radiation fog, which needs wind to mix the cooled air upward.",
   "Steam fog, which needs wind to move the air over the water."],
  "Advection needs wind to bring the air; radiation fog needs the OPPOSITE — calm, clear and a cooling surface, and wind breaks it up. That pair is the discriminator an examiner is testing. Upslope needs air moving up a slope, which is wind too, but radiation versus advection is the distinction that gets asked."),
]

# --- I.D & I.E Cross-Country & Airspace -> OralXC -------------------
APP_XC = [
 ("You are VFR in Class B airspace. What are the weather minimums?",
  ["3 statute miles and CLEAR OF CLOUDS.",
   "3 statute miles, 500 below, 1,000 above, 2,000 horizontal.",
   "5 statute miles, 1,000 below, 1,000 above, 1 mile horizontal."],
  "Class B is the only class with no cloud DISTANCE figures at all — clear of clouds is the whole requirement, because ATC is separating everyone in there. 500/1,000/2,000 is the C, D and E-below-10,000 answer; 5 and 1,000/1,000/1 belongs at or above 10,000 MSL."),
 ("At 11,500 feet MSL, 4,000 feet AGL, in Class E. What visibility and cloud clearance?",
  ["5 statute miles, 1,000 below, 1,000 above, 1 statute mile horizontal.",
   "3 statute miles, 500 below, 1,000 above, 2,000 horizontal.",
   "5 statute miles, 500 below, 1,000 above, 2,000 horizontal."],
  "Two conditions must BOTH be met to jump to the 5-and-1,000/1,000/1 row: at or above 10,000 MSL, AND more than 1,200 feet AGL. Dropping the AGL half is the standard error — at 11,500 MSL over a 10,800-foot ridge you would still be on the lower row. Note the horizontal figure becomes a MILE, not 2,000 feet."),
 ("Class G, daytime, at 900 feet AGL. What are the minimums?",
  ["1 statute mile and clear of clouds.",
   "3 statute miles, 500 below, 1,000 above, 2,000 horizontal.",
   "1 statute mile, 500 below, 1,000 above, 2,000 horizontal."],
  "At or below 1,200 AGL by DAY, Class G is 1 mile clear of clouds. At night that same airspace becomes 3 miles and 500/1,000/2,000 — with one exception: within half a mile of the runway, in the pattern at an airport with visible lights, night Class G drops back to 1 mile and clear of clouds."),
 ("A TAF forecasts a 2,000-foot ceiling and 4 miles visibility. What category is that?",
  ["MVFR — ceiling 1,000 to 3,000 AGL and/or visibility 3 to 5 statute miles.",
   "VFR, since both figures are above the Class E minimums.",
   "IFR, since the ceiling is below 3,000 feet."],
  "MVFR, Marginal VFR. The categories are LIFR below 500 and/or below 1 mile; IFR 500 to under 1,000 and/or 1 to under 3; MVFR 1,000 to 3,000 and/or 3 to 5; VFR above 3,000 and above 5. Every one is AND/OR — the WORSE of the two decides, so a 4,000-foot ceiling with 2 miles is IFR."),
 ("Squawk 7600. What has happened?",
  ["Radio failure — seven six, working on a fix.",
   "A general emergency.",
   "Unlawful interference."],
  "1200 VFR, 7500 hijack (taken alive), 7600 radio failure (working on a fix), 7700 emergency (going to heaven). Say them fast and get them right — an examiner fires these off to see whether you hesitate, and hesitating costs you more credibility than the answer is worth."),
 ("Where is a Mode C transponder required?",
  ["Class A, B and C; above Class B or C to 10,000 MSL; within the 30 NM veil; and at and above 10,000 MSL except at or below 2,500 AGL.",
   "Only inside Class A, B and C airspace.",
   "Everywhere above 10,000 feet MSL, with no exceptions."],
  "91.215, and two details decide most questions. The 30 NM veil runs from the SURFACE up to 10,000 MSL and is centred on the PRIMARY airport, not the Class B shape — so a small satellite field inside it still needs one. And the nationwide rule reads 'at and above' 10,000, so exactly 10,000 is caught."),
 ("What is the difference between a Restricted Area and a Warning Area?",
  ["Restricted needs permission from the controlling agency; a Warning Area lies outside sole US jurisdiction, so it cannot be 'restricted'.",
   "A Warning Area is more hazardous and may never be entered.",
   "Restricted is permanent; a Warning Area is activated by NOTAM only."],
  "Same kind of hazard, different legal ground — a Warning Area starts 3 NM out from the coast, where the US cannot prohibit entry, so it can only WARN. Prohibited (P) you may never enter; Restricted (R) needs permission; Alert (A) needs vigilance, not permission; an MOA you may enter, but ask the controlling agency whether it is hot."),
 ("How does a TRSA differ from Class C airspace?",
  ["Participation in a TRSA is VOLUNTARY; in Class C it is mandatory.",
   "A TRSA requires a Mode C transponder; Class C does not.",
   "A TRSA is controlled airspace; Class C is not."],
  "That is the whole difference, and it is why TRSAs are a leftover rather than a class. They are not charted as a class of airspace at all — they sit over Class D and E — and you get radar sequencing and separation if you ask for it. Class C requires two-way communication established and a Mode C transponder."),
 ("What does a solid single yellow line across the taxiway mean, as opposed to the four-line hold marking?",
  ["A taxiway-to-taxiway hold position; the four-line marking with dashes on the far side is a RUNWAY hold.",
   "The taxiway edge; you may not cross it at any time.",
   "A displaced threshold marking."],
  "The runway holding position is four lines — two solid, two dashed — and you approach from the SOLID side and may only cross with a clearance. The dashed side means you are leaving the runway and may cross without one. Getting the direction of the dashes wrong is how a taxiing aeroplane ends up on a runway it was not cleared for."),
 ("What is a displaced threshold and what may you do on the pavement before it?",
  ["Pavement not available for landing, but usable for taxi, takeoff, and the landing rollout from the other direction.",
   "Pavement not usable for any purpose at any time.",
   "A closed section of runway, marked with a yellow X."],
  "Marked with white arrows leading to a solid threshold bar. Contrast it with a BLAST PAD or stopway, marked with yellow chevrons — that is not usable for taxi, takeoff or landing at all. And a runway closed entirely carries a yellow X. Three different markings, three different permissions."),
 ("Flying a magnetic course of 270 degrees at 6,500 feet MSL, 4,000 AGL. Is that legal?",
  ["No — a course of 180 to 359 flies EVEN thousands plus 500. 6,500 is the odd-plus-500 slot.",
   "Yes — above 3,000 AGL any altitude ending in 500 is acceptable.",
   "No — the hemispheric rule applies to true course, not magnetic."],
  "More than 3,000 feet AGL: magnetic COURSE 0 to 179 flies odd thousands plus 500, and 180 to 359 flies even thousands plus 500. Westbound at 270 you want 6,500... which is wrong — you want 4,500, 6,500 belongs eastbound. Note it is COURSE, not heading: the wind correction does not change which slot you belong in."),
 ("What should your personal minimums be based on, and when may you change them?",
  ["Your own currency, experience and aircraft — and you change them on the ground, never in the air.",
   "The published 91.155 minimums for the airspace you will be in.",
   "Whatever your instructor last signed you off to fly in."],
  "The regulation is a floor written for every pilot in the country. Personal minimums are the layer that accounts for YOU — ceiling and visibility, wind and crosswind, day versus night, terrain and runway, and your own condition. The one rule is that you may only ever move them deliberately, on the ground, and not on the day it would be convenient."),
]

# --- I.F Performance -> OralPerfQ -----------------------------------
APP_PERF = [
 ("What is the basic equation for finding the centre of gravity?",
  ["Weight × Arm = Moment; CG = total moment ÷ total weight.",
   "CG = total weight ÷ total moment.",
   "CG = (empty weight + useful load) ÷ arm."],
  "Multiply to get each moment, sum both columns, then divide the total moment by the total weight. The ARM is measured from the DATUM, an arbitrary point the manufacturer picked — which is why the first thing you find in Section 6 is where the datum is, before any arithmetic starts."),
 ("What are the two kinds of drag, and how does each vary with airspeed?",
  ["Induced — the by-product of lift, greatest at LOW speed. Parasite — the airframe's resistance, greatest at HIGH speed.",
   "Induced is greatest at high speed; parasite is greatest at low speed.",
   "Both increase with airspeed; total drag therefore rises continuously."],
  "They vary in opposite directions, which is why total drag is a U-shaped curve and why the bottom of it — where the two are equal — is L/D max, your best glide speed. Parasite splits into form, skin friction and interference drag. Induced drag is the price of producing lift, which is why it dominates slow flight."),
 ("Explain Bernoulli's Principle and how it applies to the wing.",
  ["Where a fluid speeds up its pressure falls — so the faster flow over the curved upper surface is at lower pressure than beneath.",
   "Air striking the underside of the wing is deflected downward, pushing the wing up.",
   "The wing displaces a volume of air equal to the aircraft's weight."],
  "Start with the principle, then the venturi — the same volume of air must pass a narrower section, so it accelerates and its pressure drops — then say the upper surface of a wing works like one half of a venturi. Note the FAA also credits Newton: the wing deflects air DOWNWARD, and the reaction is upward. Both are right, and a good answer mentions both."),
 ("What is load factor, and why do pilots care about it?",
  ["The load the wings must support as a multiple of aircraft weight — it can overstress the structure, and it RAISES the stall speed.",
   "The weight of fuel and payload as a proportion of maximum gross weight.",
   "The ratio of lift to drag at a given angle of attack."],
  "Two consequences, and the examiner wants both. Structural is the obvious one. The stall-speed one is what kills people: stall speed rises with the SQUARE ROOT of load factor, so 2 G at 60 degrees of bank puts the stall 41 percent higher than book — and that is the base-to-final turn."),
 ("What is a spin, and what makes it different from a stall?",
  ["A stall with YAW — one wing is more stalled than the other, so the aircraft descends in a spiral.",
   "A steep spiral dive at high airspeed with the wings unstalled.",
   "A stall entered from a steep bank at high power."],
  "An uncoordinated stall. Both conditions must be present — stalled AND yawing — which is why the ball is the instrument that prevents it. A SPIRAL is the opposite trap: not stalled, airspeed increasing, and pulling harder tightens it. Telling the two apart by the airspeed indicator is the point."),
 ("What effect does GROUND EFFECT have, and at what height?",
  ["Within about one wingspan of the surface it cuts induced drag — you can lift off below flying speed and you float on landing.",
   "Within about 50 feet it increases lift by compressing air beneath the wing.",
   "It increases drag near the ground, which is why landings require more power."],
  "It interferes with the formation of wingtip vortices, so induced drag falls — a DRAG effect, not a cushion of compressed air. The takeoff trap is real: an aeroplane that flies in ground effect on a hot, heavy day may not climb out of it, which is why the soft-field technique is to stay in it and accelerate to Vx first."),
 ("Why does an aircraft stall, and at what speed?",
  ["It exceeds the critical angle of attack — at ANY airspeed, weight or attitude.",
   "Its airspeed falls below the published stall speed in the POH.",
   "Its wings can no longer generate enough lift at low power settings."],
  "An angle event, never a speed event. The published figure is just the speed at which, at max gross in 1 G unaccelerated flight, you happen to reach that angle. Load it, bank it or pull hard and the same angle arrives a great deal faster — which is exactly what an accelerated stall is and why the number in the POH is not a promise."),
 ("On a hot day at a high-elevation airport, which performance figures move and in which direction?",
  ["Longer takeoff roll, reduced rate AND angle of climb, higher true airspeed on approach and a longer landing roll.",
   "Longer takeoff roll only; once airborne performance is unaffected.",
   "Shorter takeoff roll, since the aircraft is lighter in less dense air."],
  "Density affects lift, engine power, propeller efficiency and drag — all four at once, and three of them against you. Both ends of the flight get worse, which is the half people forget: the approach is flown at the same INDICATED speed but a higher true speed, so you arrive faster over the ground and use more runway stopping."),
]

# --- I.G Systems -> OralSystems -------------------------------------
APP_SYS = [
 ("What are the purposes of the oil system? Name as many as you can.",
  ["Lubricates, cools, seals between piston and cylinder wall, cleans by carrying contaminants away, cushions, and protects against corrosion.",
   "Lubricates and cools only; the cooling is incidental to the lubrication.",
   "Lubricates, cools and provides hydraulic pressure for the propeller governor."],
  "Six, and COOLING is the one people are surprised by — oil carries a substantial share of the heat away from the cylinders in an air-cooled engine, which is why oil temperature is a systems indication and not a nicety. Sealing between the piston and the cylinder wall is the other one that gets left out."),
 ("What does the hydraulic system operate in a light aircraft?",
  ["The wheel brakes — and, on aircraft that have them, retractable landing gear and constant-speed propellers.",
   "The flaps and the wheel brakes.",
   "The flight controls and the nosewheel steering."],
  "In your 172 the answer is essentially the brakes: the flaps are ELECTRIC and the flight controls are cables and pushrods. Knowing what is NOT hydraulic in your aeroplane is as much the point as knowing what is, because it tells you what an electrical failure costs you and what it does not."),
 ("What does the electrical system power, and what does it NOT?",
  ["It powers the radios, lights, flaps, fuel gauges and turn coordinator — but NOT the engine, which runs on its own magnetos.",
   "It powers everything including the ignition, which is why the master must stay on.",
   "It powers only the radios and lights; the instruments are all mechanical."],
  "The magnetos are engine-driven and self-generating, so a total electrical failure is a communication and equipment emergency, not an engine one. In the 172 the flaps are electric, which is the one that surprises people on a dead bus — plan a no-flap landing, longer and flatter, and expect to float."),
 ("Why is the alternator's output voltage slightly higher than the battery's?",
  ["The difference in voltage is what drives current into the battery and keeps it charged.",
   "To compensate for voltage lost in the wiring to the instrument panel.",
   "To allow the battery to be used as a backup without switching."],
  "Current flows from higher potential to lower, so the alternator must sit above the battery for the battery to receive anything. That is also why the AMMETER reads positive when charging: it is showing you the direction of that flow, and a steady negative reading means the alternator has stopped supplying and the battery is carrying the aircraft."),
 ("What type of ignition system does your aircraft have, and why is it built that way?",
  ["Two engine-driven magnetos with two plugs per cylinder — for redundancy and a more complete burn.",
   "A single magneto with an electrical backup ignition from the battery.",
   "An electronic ignition drawing from the alternator, with magneto backup."],
  "Two independent systems, each firing one plug per cylinder, neither of them connected to the aircraft's electrical system. Redundancy is the obvious reason; the second is combustion — two flame fronts burn the charge more completely than one, which is why you lose 75 to 150 RPM when you cut one at run-up."),
 ("Describe your engine in the terms the examiner expects.",
  ["Lycoming, four-cylinder, horizontally opposed, air-cooled, normally aspirated, direct drive.",
   "Continental, six-cylinder, horizontally opposed, liquid-cooled, turbocharged.",
   "Lycoming, four-cylinder, in-line, air-cooled, fuel-injected, geared."],
  "Six descriptors and they want all six. NORMALLY ASPIRATED means no turbo or supercharger — which is why your performance falls off with altitude and why there is no manifold pressure limit to worry about. DIRECT DRIVE means the propeller turns at engine speed, with no reduction gearbox between them."),
 ("What fuel does your aircraft take, what colour is it, and what if it is unavailable?",
  ["100LL, dyed BLUE — and if unavailable, use the next HIGHER grade, never a lower one.",
   "100LL, dyed green — and if unavailable, any automotive fuel of 91 octane or above.",
   "100LL, dyed blue — and if unavailable, the next lower grade, which burns cooler."],
  "Blue for 100LL, green for 100, clear or straw for jet fuel. Higher grade takes more pressure before detonating, so going up is conservative and going down invites the failure. Clear fuel going into a piston aeroplane is the one to stop the truck for — misfuelling is not a theoretical accident."),
 ("The engine runs rough at cruise and you suspect a fouled plug. What do you try?",
  ["Lean the mixture at cruise power to raise combustion temperature and burn the deposit off.",
   "Enrich the mixture fully, which will wash the deposit away.",
   "Apply carburettor heat, which will melt the deposit."],
  "Fouling is usually lead or carbon from running too RICH, so the cure is the opposite — lean it and let the extra heat clean it. Carb heat treats ICE, which has a different signature: a gradual RPM loss that recovers ABOVE the original figure after the initial drop. Diagnose before you act; the two look similar and the responses are opposite."),
]

# --- I.H Human Factors -> OralAeromed --------------------------------
APP_HF = [
 ("What is spatial disorientation, and what is the remedy?",
  ["Losing your sense of position, attitude or motion relative to the earth — and the remedy is to trust and fly the INSTRUMENTS.",
   "A visual illusion on approach, remedied by going around.",
   "A form of motion sickness, remedied by fresh air and slow breathing."],
  "The senses that keep you upright on the ground — inner ear, seat of the pants, eyes — all give false readings when they are subjected to the forces of flight. They cannot be trained out of it; they can only be OVERRIDDEN. That is why 61.109 requires 3 hours of flight by reference to instruments even for a VFR certificate."),
 ("What causes hyperventilation, and how do you treat it?",
  ["Excessive rate and depth of breathing blowing off carbon dioxide — treated by slowing the breathing, talking aloud, or breathing into a bag.",
   "Too much carbon dioxide in the blood — treated with supplemental oxygen.",
   "Insufficient oxygen at altitude — treated by descending immediately."],
  "It is a CO2 problem, not an oxygen one, which is why the treatment is the opposite of hypoxia's. But early symptoms overlap, so the order is: treat for hypoxia FIRST — oxygen on, system checked — then consciously slow the breathing. Talking aloud works because it forces a normal rhythm on you."),
 ("Why is an ear block worse on descent, and how do you clear it?",
  ["Descending, air must get INTO the middle ear against a tube the pressure tends to squeeze shut — cleared with the Valsalva.",
   "Descending air is colder, which constricts the eustachian tube.",
   "It is equally likely on climb and descent; the difference is perception."],
  "Climbing, the expanding middle-ear air escapes fairly freely. Descending, you need air to go the hard way. Valsalva — pinch the nostrils, close the mouth, blow gently. Chewing, yawning and swallowing open the tube too. If it will not clear, CLIMB BACK UP and descend more slowly. A maxillary sinus block refers pain to the upper teeth."),
 ("You have a head cold and take an oral decongestant so you can fly. What is wrong with that plan?",
  ["Oral decongestants impair pilot performance — so the treatment can itself make you unfit.",
   "Nothing, provided you wait 8 hours after the dose.",
   "Decongestant sprays are prohibited by regulation; oral forms are acceptable."],
  "The AIM says sprays give inadequate protection and that oral decongestants impair performance, so the sequence people reach for — feel blocked, take something, go fly — is exactly backwards. The correct answer to flying with a cold is not to fly with a cold. And remember the CONDITION can disqualify you even where the drug does not."),
 ("A featureless approach over water or snow at night. What will you feel, and what will you do about it?",
  ["You will feel HIGH, so you will fly LOW — guard against it with the VASI/PAPI and the altimeter.",
   "You will feel low, so you will fly high and risk a long landing.",
   "Featureless terrain produces no illusion as long as the runway is lit."],
  "Almost every approach illusion drives you LOW: narrow runway, upslope, rain, haze, black hole. The exceptions that push you HIGH are a wide runway, downsloping terrain, bright approach lighting, and penetrating fog. The defence is the same in every case — fly the glide path indication and the instruments, not the picture."),
 ("How long must you wait after a non-decompression dive before flying at 9,500 feet MSL?",
  ["24 hours — above 8,000 feet the dive type stops mattering.",
   "12 hours, because it was a non-decompression dive.",
   "8 hours, the same as the bottle-to-throttle rule."],
  "The AIM gives 12 hours only for a non-decompression dive AND a flight below 8,000 feet. Above 8,000 it is 24 hours after ANY dive, and a decompression dive is 24 hours whatever the altitude. Note the threshold is ACTUAL FLIGHT ALTITUDE above MSL, not cabin altitude — the AIM says so explicitly."),
]

APPENDS = {
    'OralPrereq':  APP_PREREQ,
    'OralInop':    APP_INOP,
    'OralWxQ':     APP_WX,
    'OralXC':      APP_XC,
    'OralPerfQ':   APP_PERF,
    'OralSystems': APP_SYS,
    'OralAeromed': APP_HF,
}

# ===================================================================
# PART B — SCENARIOS
# ===================================================================
# One situation per bank, developing question by question across Tasks,
# the way a DPE actually runs the oral.

SCEN_XC = [
 ("SCENARIO — You have planned KGAI to KLNS, 62 NM, departing 09:00. The examiner opens with your nav log. First question: why did you pick the cruising altitude you did?",
  ["Terrain and obstacle clearance, gliding distance to a field, the hemispheric rule, the wind, and staying clear of the airspace.",
   "The hemispheric rule alone, since that is the only regulatory constraint.",
   "The altitude that gives the highest true airspeed for the shortest time en route."],
  "Five considerations, and the examiner is listening for whether ONE of them is glide range — that is the risk-management element hiding in a planning question. The hemispheric rule is regulatory but it only tells you which of several legal altitudes to pick, not which is the right one for this flight."),
 ("SCENARIO, continued — Your route passes within the Mode C veil around KBWI but well outside the Class B shelves, at 3,500 MSL. What do you need?",
  ["A Mode C transponder — the veil applies from the surface to 10,000 MSL regardless of your distance from the shelves.",
   "Nothing extra, since you are clear of the Class B airspace itself.",
   "A Class B clearance, because the veil is part of the Class B airspace."],
  "The veil is a SEPARATE rule from the Class B, drawn 30 NM around the PRIMARY airport, and it has no floor. Being beside or beneath a shelf does not release you. It does not, however, require a clearance — that is only for entering the Class B itself, and 'cleared into the Bravo' must be heard explicitly."),
 ("SCENARIO, continued — The examiner points at 2,049 with (1,150) beneath it on your route. What are those numbers and which one do you use?",
  ["2,049 is the top in MSL and 1,150 is its height AGL — you plan from the MSL figure, because your altimeter reads MSL.",
   "2,049 is the terrain elevation and 1,150 is the obstacle's height above it.",
   "2,049 is the height AGL and 1,150 is the MSL elevation of the base."],
  "Bold on top is MSL, parenthesised beneath is AGL. Using the AGL figure gives an answer that looks perfectly reasonable and is 900 feet low here. The MEF in the quadrangle is a different number again — the highest thing in the box, with an allowance for obstacles of unknown height, and it is a DATUM, not a minimum altitude."),
 ("SCENARIO, continued — What fuel are you required to carry, and what will you actually carry?",
  ["91.151 requires destination plus 30 minutes at normal cruising speed by day — WIFA requires 1 hour, and that is what I plan to.",
   "Destination plus 45 minutes, since that is the safer figure.",
   "Destination plus 30 minutes computed at best-endurance speed."],
  "Give the regulation AND your school's stricter rule; that pair is the answer an examiner is fishing for, because it shows you know the FAR is a floor. The reserve is computed at NORMAL CRUISING speed, not the most economical setting you could theoretically fly — that distinction is written into the rule."),
 ("SCENARIO, continued — Your destination has a part-time tower that closes at 18:00 and you may land after that. What changes?",
  ["The airspace reverts to Class E or Class G depending on what is charted — and the weather minimums change with it. I use CTAF.",
   "The airspace always becomes Class G, and no radio calls are required.",
   "The airspace remains Class D and two-way communication must still be established."],
  "Check the chart supplement: most such fields become Class E, some become Class G. Assuming Class G is the dangerous default because it is the most permissive — and Class G at night is 3 miles and 500/1,000/2,000, which is a meaningfully harder minimum than the 1 mile you get by day."),
 ("SCENARIO, continued — You will now arrive after dark. What three separate clocks apply?",
  ["Position lights from sunset to sunrise; passenger currency from 1 hour after sunset to 1 hour before sunrise; logging night time uses civil twilight.",
   "All three use the period from sunset to sunrise.",
   "Position lights and logging use civil twilight; passenger currency uses sunset to sunrise."],
  "Three different definitions of 'night' in three different rules, and the examiner asks precisely because they are easy to merge. Add the equipment question: 91.205(c) brings FLAPS in — Fuses, Landing light if for hire, Anti-collision lights, Position lights, Source of electrical power."),
 ("SCENARIO, continued — Ten minutes from the destination the field goes below your personal minimums. Which model are you running and what is the first step?",
  ["DECIDE — and the first step is DETECT: say out loud that the situation has changed.",
   "3P, because a hazard has been perceived.",
   "IMSAFE, to reassess my own fitness to continue."],
  "Something has already changed, so DECIDE applies — it is the reactive model. 3P is what you ran on the ground. The step people skip is the first one: a pilot who has not ADMITTED the situation changed carries on flying the plan they made at 08:00, which is the whole mechanism behind get-there-itis."),
 ("SCENARIO, continued — You decide to divert. What is the very first action?",
  ["Turn toward the alternate immediately, then compute the heading, time and fuel.",
   "Complete a full navigation log to the alternate before changing heading.",
   "Contact Flight Service for a recommendation before committing."],
  "Turn first, compute second. Every minute head-down with a plotter is a minute flying deeper into what you decided to leave. Estimate the heading off the chart by eye, start the turn and the clock, then refine. The ACS is grading the DECISION here far more than the arithmetic."),
 ("SCENARIO, continued — While diverting you become unsure of your position. What is the sequence?",
  ["Climb, Communicate, Confess, Comply, Conserve.",
   "Confess, Climb, Communicate, Comply, Conserve.",
   "Communicate, Climb, Confess, Conserve, Comply."],
  "CLIMB first, and the order is the point — height buys radio range, radar coverage, visibility and gliding options all at once. Confessing from low altitude where nobody can hear you achieves nothing. Then communicate, confess plainly rather than dressing it up, comply with what you are given, and conserve fuel throughout."),
 ("SCENARIO, continued — You elect to land at an unfamiliar field. Where do you find its pattern altitude and runway lengths?",
  ["The Chart Supplement — it carries pattern altitude, runway dimensions and surface, lighting, frequencies and remarks.",
   "The sectional chart, which prints pattern altitude beside the airport symbol.",
   "The POH performance section, which lists suitable airports."],
  "The sectional gives you existence, elevation, longest runway and the CTAF; the DETAIL is in the Chart Supplement, formerly the Airport/Facility Directory. Remarks are where the noise procedures, the obstructions and the 'right traffic runway 14' live — and a right-hand pattern at an unfamiliar field is exactly the surprise you do not want."),
 ("SCENARIO, continued — You land safely but 40 minutes late, and nobody has heard from you. Does that matter?",
  ["Only if I filed a VFR flight plan — in which case I must CLOSE it, or search and rescue begins.",
   "Yes — ATC will initiate a search for any VFR aircraft that does not arrive as planned.",
   "No — VFR flights are never tracked, so no action follows."],
  "A VFR flight plan is voluntary and buys you exactly one thing: search and rescue. It gives no ATC service, no clearance and no flight following. And nobody closes it for you — the other half of the answer, and the reason a forgotten flight plan launches an aircraft to look for you."),
 ("SCENARIO, closing — The examiner asks what single thing would have made this flight easier. What answer shows good judgment?",
  ["Setting and writing down personal minimums beforehand, so the diversion decision was already made on the ground.",
   "Filing IFR instead, which removes the weather constraint.",
   "Departing earlier, since the weather was forecast to deteriorate."],
  "Departing earlier is a fine answer and it is not the one being graded. The ACS Risk Management elements are about having a STANDARD you set while calm, so that a decision under pressure is a lookup rather than a negotiation. IFR is outside your certificate and answering it tells the examiner you reached past your privileges."),
]

SCEN_AIRWORTHY = [
 ("SCENARIO — On preflight you find the landing light burned out. Day VFR local flight, no MEL for the aircraft. Walk the chain.",
  ["91.213(d): not part of the VFR-day type certificate, not required by 91.205 for this flight, not required by an AD, not on the equipment list — then deactivate or remove, and placard INOPERATIVE.",
   "Note it in the aircraft records and fly; inoperative equipment needs no further action.",
   "The aircraft is unairworthy until it is replaced."],
  "Four filters, then two actions, then a determination that it is not a hazard. For a private day VFR flight a landing light passes every filter — 91.205(c)(4) only requires one when the aircraft is operated FOR HIRE. Deactivate or remove AND placard: both, not one."),
 ("SCENARIO, continued — Same aeroplane, same burned-out light, but now the flight is at night. What changes?",
  ["The chain fails at the second filter — the item is required by 91.205(c) for this kind of flight, so the placard route is not available.",
   "Nothing — a landing light is never required for a private flight.",
   "It becomes acceptable, since night flights carry a landing light only as a recommendation."],
  "The same aeroplane can be legal by day and illegal by night, and that is the whole point of the scenario. Note the wording of 91.205(c)(4): the landing light is required for aircraft operated FOR HIRE — so argue it carefully, and say that either way you would not fly a night flight without one."),
 ("SCENARIO, continued — You check Section 6 and find the item marked '-R' in the equipment list. What does that mean?",
  ["Required — it may not be removed or deactivated, so 91.213(d) fails at the equipment-list filter.",
   "Recommended — the manufacturer advises carrying it but it is not required.",
   "Removable — it may be taken out at the operator's discretion."],
  "This is your guide's engine-spinner question. The equipment list in Section 6 is aircraft-specific and it is a filter in its own right: an item can be absent from 91.205 and still be required BY THE LIST. The answer to 'can I fly without X' is never from memory — it is from Section 6."),
 ("SCENARIO, continued — The examiner asks how you know this POH belongs to this aeroplane.",
  ["Each POH carries a serial number — I check it against the registration certificate and the data plate on the airframe.",
   "All POHs for a given model are interchangeable within that model.",
   "The POH is generic; only the weight and balance data is aircraft-specific."],
  "A POH is tied to one serial number, and a 172S POH from a different airframe has the wrong weight and balance and possibly the wrong equipment list. The registration and the data plate are the two cross-references. This is a cheap question and losing it looks careless."),
 ("SCENARIO, continued — You open the maintenance records. What are you looking for, in what order?",
  ["Annual, 100-hour if applicable, transponder and altimeter checks, ELT, and AD compliance — with dates and tach times.",
   "The annual inspection sign-off, which confirms everything else was checked.",
   "The ARROW documents, which are the legal proof of airworthiness."],
  "AV1ATE walks you through it. Two things students forget: the AD list, which is the part that is genuinely a search rather than a lookup; and that ARROW proves the aircraft is registered and certificated, NOT that it is airworthy today. This is a SKILL element — the examiner watches you do it, not describe it."),
 ("SCENARIO, continued — It is a school aeroplane used for instruction. Which inspection applies that would not on a privately owned one?",
  ["The 100-hour — it attaches to flight instruction for hire in an aircraft the instructor provides.",
   "The annual, which only applies to commercially operated aircraft.",
   "The transponder check, which is required only for aircraft used for hire."],
  "The 100-hour is triggered by what the aircraft is USED FOR, not by what it is. The annual applies to every aircraft and the transponder check applies to any USE of a transponder, VFR or IFR. Of the six AV1ATE items only two are IFR-only: the 30-day VOR check and the 24-month altimeter and static check."),
 ("SCENARIO, continued — The transponder check is 25 months old. May you fly the local day VFR flight?",
  ["No, not with the transponder in use — 91.413 requires the test every 24 calendar months for ANY use, VFR or IFR.",
   "Yes — the transponder check is an IFR-only requirement.",
   "Yes — a 30-day grace period applies to the 24-month checks."],
  "The rule prohibits USING an out-of-date transponder, not flying the aeroplane. So the real answer is layered: is one REQUIRED where you are going (91.215), and if it is installed and you intend to squawk, is it current (91.413)? In the Washington area the answer to the first is almost always yes."),
 ("SCENARIO, continued — You discover an AD that became effective last month and has not been complied with. What is the aircraft's status?",
  ["Not airworthy — AD compliance is mandatory under Part 39 and it does not conform to its type certificate until it is done.",
   "Airworthy, provided the AD is a recurring one rather than a one-time AD.",
   "Airworthy until the next annual inspection, when compliance will be verified."],
  "Part 39 makes an AD a regulation, not advice — unlike a manufacturer's SERVICE BULLETIN, which is advisory unless an AD adopts it. Note that even a Special Flight Permit to reach maintenance requires every DUE AD to be complied with first: the FAA will fly you out of an expired inspection, not out of a known unsafe condition."),
 ("SCENARIO, continued — Who was responsible for that lapse, and who is responsible now?",
  ["The owner or operator under 91.403 for maintaining it — and ME under 91.7(b) for determining it is in condition for safe flight.",
   "The owner alone; the pilot's responsibility begins only once airborne.",
   "The mechanic who signed the last annual inspection."],
  "Both are true at once and the examiner wants both. 91.403 is the ongoing maintenance duty. 91.7(b) makes the PIC responsible for the determination BEFORE flight and for discontinuing the flight when an unairworthy condition occurs. You cannot point at the owner after the fact."),
 ("SCENARIO, closing — You replace the landing light bulb yourself. Is that legal, and what do you write?",
  ["Yes if I own or operate it — Part 43 Appendix A(c) covers it, and 43.9 wants the work, the date, and my name, signature and certificate number.",
   "No — all bulb replacement requires an A&P mechanic.",
   "Yes, and no record is required for preventive maintenance performed by a pilot."],
  "Three constraints on the privilege: the listed jobs only, an aircraft you own or operate, and not one run under Part 121, 129 or 135. The certificate NUMBER is the part people leave out of the entry, and it goes in the AIRCRAFT maintenance records — not your flight logbook."),
]

SCEN_WX = [
 ("SCENARIO — It is 06:30 at KGAI. Temperature 12, dew point 11, wind calm, clear sky. What do you expect in the next hour?",
  ["Radiation fog — calm, clear, a cooling surface and a spread of 1 degree is the recipe.",
   "Advection fog rolling in from the coast.",
   "Nothing — a clear sky and calm wind are the most benign conditions possible."],
  "A spread within 5 degrees means visible moisture is likely; a spread of 1 with calm wind and a clear night means the ground has been radiating heat away all night and the air at the surface is about to reach its dew point. The benign-looking conditions ARE the mechanism, which is what makes it the classic trap."),
 ("SCENARIO, continued — You delay two hours. What will break the fog up, and what would have made it worse?",
  ["Surface heating and a light wind will lift and disperse it — a continued calm and a moist surface would have held it.",
   "Only a frontal passage will clear radiation fog.",
   "Increasing wind will deepen it by mixing more moisture in."],
  "Radiation fog is a calm-wind phenomenon, so wind is its enemy — the opposite of ADVECTION fog, which REQUIRES wind to carry warm moist air over a cold surface. That pair is the discriminator examiners test. Upslope needs air moving up a slope; steam fog needs cold air over warm water."),
 ("SCENARIO, continued — Airborne at 09:30 en route. The AIRMET Tango you read at 06:00 was valid for how long, and what did it cover?",
  ["6 hours — moderate turbulence, sustained surface winds of 30 knots or more, and non-convective low-level wind shear.",
   "4 hours — severe turbulence and clear air turbulence.",
   "2 hours — thunderstorm-related turbulence and wind shear."],
  "AIRMET is 6 hours and MODERATE: Tango turbulence, Sierra IFR and mountain obscuration, Zulu icing and freezing levels. 4 hours and SEVERE is a SIGMET, non-convective. 2 hours and thunderstorms is a Convective SIGMET, issued at 55 past the hour. Three products, three validities — know which one you are quoting."),
 ("SCENARIO, continued — Flight Service now reports a Convective SIGMET on your route. What does it tell you that the text does not spell out?",
  ["Severe or greater turbulence, severe icing and low-level wind shear — all implied automatically.",
   "Moderate turbulence and icing, at the levels stated in the text.",
   "Nothing beyond what is written; the text is exhaustive."],
  "Those three are implied by the product itself, which is why they are not listed. It is issued for surface winds of 50 knots or more, hail three-quarters of an inch or larger, tornadoes, or embedded thunderstorms of any intensity — and 'embedded of any intensity' is the clause that should end the discussion for a VFR flight."),
 ("SCENARIO, continued — How far do you stay from it, and why is 'clear of the cloud' not an answer?",
  ["20 NM from a severe or heavy-precipitation storm — turbulence reaches 20 miles from the radar echo edge and hail falls several miles from the visible cloud.",
   "5 NM is sufficient, provided the cloud is visually avoided.",
   "Clear of the cloud is sufficient in VMC, since the hazard is inside it."],
  "Two different numbers and both belong outside the cloud. Hazardous turbulence to 20 miles from the ECHO EDGE, hail several miles from the nearest VISIBLE cloud. Blue sky between you and a thunderstorm is not protection — which is exactly why the AIM states a distance rather than 'avoid the cloud'."),
 ("SCENARIO, continued — Ahead of the storm you meet an increasing headwind on the approach and rise above the glide path. What is happening?",
  ["Possible microburst — the performance-INCREASING side comes first, and the downdraft and tailwind follow.",
   "Normal wind gradient; reduce power and re-establish the glide path.",
   "An updraft from surface heating, which is not a hazard on approach."],
  "The phenomenon opens by making the aeroplane perform BETTER, so the instinct is to pull the power back — and that is the configuration you are in when the downdraft and then the tailwind arrive. An unexplained performance increase on short final is a reason to go around, not a reason to reduce power."),
 ("SCENARIO, continued — You divert around it. Temperature at your altitude is +2 and you are in visible moisture. What is the concern?",
  ["Structural icing — the surface temperature can be at or below freezing even with the OAT slightly above.",
   "None — icing requires an outside air temperature below 0 Celsius.",
   "Carburettor icing only; structural icing is impossible above freezing."],
  "Two conditions: visible moisture AND the surface temperature at or below 0 — and the temperature that counts is at the COLLECTING SURFACE, which cools below OAT. Clear ice from large drops freezing slowly, rime from small drops freezing fast. Either way the response is the same: leave the visible moisture."),
 ("SCENARIO, continued — You pick up ice. What do you do, and what has it already cost you?",
  ["Leave the visible moisture — descend below the bases, climb above the tops or turn back. It has raised my stall speed and cut my power at the same time.",
   "Increase speed to warm the airframe by friction and continue.",
   "Maintain altitude and wait; light ice sublimates in cruise."],
  "Both ends of the margin close at once: disrupted airflow separates early so the stall arrives sooner, while the same ice on the propeller and intake costs you the power you would need. That is why there is no 'manage it' option in a 172 — the only answer is to get out of the conditions, and the pitot heat goes on."),
 ("SCENARIO, continued — You land at an alternate. The altimeter setting there is 29.62 and you never reset it from 30.02. What were you doing?",
  ["Flying LOWER than the altimeter indicated — high to low, look out below.",
   "Flying higher than indicated, with extra terrain clearance.",
   "Nothing — the error cancels once the aircraft is level."],
  "A 0.40 inch error is about 400 feet, and it is 400 feet you did not have. The mnemonic belongs to flying from HIGH pressure to LOW pressure — and to flying from WARM air into COLD, which produces the same error. Attaching it to the warm case inverts the whole answer."),
 ("SCENARIO, closing — The examiner asks at what point in that flight you should have turned around.",
  ["When the destination went below the personal minimums I set on the ground — before the diversion became a weather avoidance problem.",
   "When I first picked up ice, which is the point the flight became unsafe.",
   "When the Convective SIGMET was issued, since that is a regulatory prohibition."],
  "A Convective SIGMET is not a prohibition and ice was already too late — both answers put the decision after the situation had taken it from you. The one the ACS is grading is the personal minimum, set while calm on the ground, which makes the turn a LOOKUP rather than a negotiation at 3,500 feet."),
]

SCEN_INFLIGHT = [
 ("SCENARIO — Cruising at 4,500 feet, 15 NM from the nearest field, the engine begins running rough. First action?",
  ["Fly the aeroplane first — establish best glide attitude and pick a field, THEN start diagnosing.",
   "Immediately switch tanks and apply carburettor heat before anything else.",
   "Transmit a mayday on 121.5 and await instructions."],
  "Aviate, navigate, communicate — and the order is not a slogan, it is a priority list for exactly this moment. A rough engine may still be making power, so you are not committed to a forced landing; but the glide picture and a chosen field cost you nothing and buy you everything if it quits while you are troubleshooting."),
 ("SCENARIO, continued — Conditions are 15 C and humid. What do you suspect first, and what confirms it?",
  ["Carburettor ice — apply carb heat; the RPM drops first, then RISES above the original figure, often roughly as it clears.",
   "Fuel starvation — switch tanks and watch for an immediate smooth recovery.",
   "A fouled plug — enrich the mixture fully and wait."],
  "Below 70 F with humidity above 80 percent is squarely in the FAA's most-likely band. The RECOVERY above the original RPM is the confirmation, and roughness while it clears is the melt water going through the engine — a good sign, not a reason to pull the heat back off. A fouled plug is cured by LEANING, not enriching."),
 ("SCENARIO, continued — Carb heat makes no difference and the roughness persists. What next?",
  ["Work the restart items — carb heat, fuel selector BOTH, mixture, primer locked, fuel pump, ignition — while continuing toward the field.",
   "Shut the engine down to prevent damage and glide to the field.",
   "Descend rapidly to below 1,000 AGL to improve the options."],
  "A rough engine still producing partial power is worth more than a stopped one, so you troubleshoot while flying toward a landable field, not instead of it. Shutting down a running engine on purpose removes the one thing still helping you. Descending early throws away glide range for nothing."),
 ("SCENARIO, continued — The engine stops. You are at 4,000 AGL. What is your gliding speed and what governs the distance?",
  ["68 KIAS at max gross — and distance is governed by L/D max, which is a peak, so flying either side of it costs you range.",
   "Best rate of climb speed, since it gives the most time aloft.",
   "As slow as possible to maximise time for a restart."],
  "68 KIAS is best glide for your C172S at max gross, and it is L/D max — the peak of the curve, so faster OR slower both shorten the glide. Minimum sink is a slightly slower speed and it buys TIME, not distance. Different speeds for different problems: reaching a field versus working a restart."),
 ("SCENARIO, continued — Before the off-airport touchdown, what do you do and why?",
  ["Secure the fuel and electrical systems and POP THE DOORS — so a deformed airframe cannot jam them shut.",
   "Lock the doors to maintain structural integrity of the cabin.",
   "Nothing further; all effort goes on the landing itself."],
  "Fuel and electrical off cuts the fire risk; the doors are about getting out afterwards. It is in the WIFA pre-takeoff brief for a reason. Fly it so the WINGS absorb the impact rather than the cabin, and announce your intentions — somebody knowing where you went is worth the ten seconds."),
 ("SCENARIO, alternative — Same flight, but instead the ammeter shows a steady discharge. What does that mean and what do you do?",
  ["The alternator has stopped supplying and the battery is carrying the aircraft — shed load, keep what I need to land, and land.",
   "The battery is charging normally after a period of high electrical demand.",
   "The alternator output voltage is too high and must be reduced."],
  "Positive is the alternator charging the battery; negative is the battery being drained. You are on a clock measured in tens of minutes. Shed the strobes, the extra radio, the landing light until short final. Remember the ENGINE is unaffected — magnetos are self-generating — so this is a systems problem, not a power-off emergency."),
 ("SCENARIO, continued — The flaps will not extend on the approach. What changes about your landing?",
  ["Flaps are ELECTRIC in the 172 — plan a flatter, faster, longer approach and expect to float, on the longest runway available.",
   "Nothing — flap position does not materially affect approach speed or distance.",
   "Use a steeper approach at a lower speed to compensate for the lost drag."],
  "Without flaps you have less drag and a higher stall speed, so the approach is flatter and the touchdown faster, and the landing roll grows. A steeper, slower approach is the wrong instinct — that is where a no-flap landing turns into a stall. Say which runway you would want; that is the risk management half."),
 ("SCENARIO, alternative — The static port ices over in the climb. What do the instruments do and what do you do?",
  ["Altimeter freezes, VSI reads zero, airspeed reads LOW in the climb — I open the alternate static source.",
   "Altimeter freezes, VSI reads zero, airspeed reads high in the climb.",
   "All three instruments fail to zero and cannot be recovered."],
  "All three are static instruments. With trapped pressure too HIGH for your new altitude the differential shrinks and the ASI under-reads — the dangerous direction, because you think you are slower than you are. The alternate source uses cabin air at slightly LOWER pressure, so afterwards expect the altimeter and airspeed to read a little high."),
 ("SCENARIO, alternative — You smell nothing but have a headache and feel drowsy, with the cabin heat on. What is it and what do you do?",
  ["Carbon monoxide — shut the cabin heat OFF, open the fresh air vents, and land as soon as practical.",
   "Hypoxia — descend to a lower altitude and continue the flight.",
   "Hyperventilation — slow the breathing and continue."],
  "CO is colourless, odourless and tasteless, so smelling nothing proves nothing. Most light-aircraft heaters pass cabin air over the exhaust manifold, so a cracked manifold feeds exhaust straight in — which is why the HEAT goes off, not just the vents open. It is HYPEMIC hypoxia: the blood cannot carry oxygen because CO has taken the haemoglobin."),
 ("SCENARIO, closing — You land safely with substantial damage to the airframe. What are your reporting duties?",
  ["Notify the NTSB immediately, and file the written report within 10 days.",
   "Notify the FAA FSDO within 48 hours and file a NASA report.",
   "File a written NTSB report within 7 days; no immediate notification is needed."],
  "49 CFR 830 — the NTSB, not the FAA, and Title 49, not 14. Substantial damage makes it an ACCIDENT, so immediate notification plus Form 6120.1 within 10 days. The 7-day report belongs to an aircraft overdue and believed missing. A NASA ASRS report is voluntary and separate, and it is not a substitute for either."),
]

SCEN_BANKS = [
    ("ScenXC", "The Cross-Country", SCEN_XC,
     [("A DPE walks through a nav log", "https://www.youtube.com/results?search_query=private+pilot+checkride+oral+cross+country+nav+log+walkthrough+DPE"),
      ("Diversion and lost procedures", "https://www.youtube.com/results?search_query=diversion+lost+procedures+five+Cs+private+pilot")]),
    ("ScenAirworthy", "The Broken Aeroplane", SCEN_AIRWORTHY,
     [("91.213 and inoperative equipment", "https://www.youtube.com/results?search_query=91.213+inoperative+equipment+MEL+KOEL+placard+explained"),
      ("Proving airworthiness from the logbooks", "https://www.youtube.com/results?search_query=prove+aircraft+airworthy+maintenance+logbooks+checkride+oral")]),
    ("ScenWx", "The Weather Day", SCEN_WX,
     [("Reading a real weather briefing", "https://www.youtube.com/results?search_query=VFR+weather+briefing+go+no+go+decision+private+pilot"),
      ("Thunderstorms, microbursts and icing", "https://www.youtube.com/results?search_query=thunderstorm+microburst+structural+icing+avoidance+private+pilot")]),
    ("ScenInflight", "It Goes Wrong In Flight", SCEN_INFLIGHT,
     [("Engine failure and the forced landing", "https://www.youtube.com/results?search_query=engine+failure+in+flight+forced+landing+best+glide+cessna+172"),
      ("Electrical failure and partial power loss", "https://www.youtube.com/results?search_query=alternator+failure+partial+power+loss+cessna+172+procedure")]),
]

SCEN_DESC = {
    'ScenXC': "One flight, KGAI to KLNS, developing question by question — altitude choice, airspace, the chart, fuel, an arrival after dark, weather at the destination, the diversion, being unsure of position, and the debrief. This is how a DPE actually runs the oral: not Task by Task, but one situation across all of them.",
    'ScenAirworthy': "One burned-out landing light, followed all the way down: the 91.213 chain by day, the same fault at night, Section 6 and the equipment list, the logbooks, an out-of-date transponder, an outstanding AD, and who carries the responsibility.",
    'ScenWx': "One day of weather, from a 1-degree spread at 06:30 through fog, an AIRMET, a Convective SIGMET, a microburst on approach, structural icing and an altimeter setting nobody updated — ending with the question of where the decision should have been made.",
    'ScenInflight': "Things going wrong with the aeroplane while you are flying it, inside PPL scope: a rough engine, carburettor ice, a full failure and the forced landing, an alternator discharge, no flaps, a blocked static port and carbon monoxide.",
}

SCEN_SUB = "Scenarios — The Real Oral"
