# -*- coding: utf-8 -*-
"""Oral Exam category data. Built on FAA-S-ACS-6C (Nov 2023 edition, effective
31 May 2024, incorporated by reference at 14 CFR 61.14), 14 CFR, and the AIM.
Correct answer is index 0 here; the app shuffles at render time."""

# ---------------------------------------------------------------- definitions
DEFS = [
("OralACS", "How the ACS Works", "The Examiner's Rulebook",
 "The Airman Certification Standards is the document your examiner builds the test from — FAA-S-ACS-6C, the November 2023 edition, made legally binding by 14 CFR 61.14. Knowing its shape tells you the minimum surface area of the oral.",
 ["Area of Operation ➔ a phase or subject block, numbered with Roman numerals. I is Preflight Preparation, II is Preflight Procedures",
  "Task ➔ a specific activity inside that Area, lettered. I.B is Airworthiness Requirements",
  "K elements ➔ Knowledge. The stem reads: the applicant demonstrates understanding of",
  "R elements ➔ Risk Management. The applicant is able to identify, assess and mitigate risk associated with",
  "S elements ➔ Skill. The applicant exhibits the skill to",
  "The code ➔ PA.I.D.K4 reads Private Airplane, Area I, Task D, Knowledge element 4",
  "Plan of Action ➔ what the examiner must cover: at least one K element and one R element per Task, ALL S elements, and every subject you missed on the written",
  "The consequence ➔ your knowledge test report codes are a guaranteed question list, and your instructor had to sign that you were remediated on them (61.39a6)"]),

("OralAreas", "Areas of Operation", "What Gets Tested",
 "The Tasks in Areas I and II — the ground portion. Titles are verbatim from the ACS. Task I.I and Task II.E are seaplane only and do not apply to your ASEL checkride.",
 ["I.A ➔ Pilot Qualifications",
  "I.B ➔ Airworthiness Requirements",
  "I.C ➔ Weather Information",
  "I.D ➔ Cross-Country Flight Planning",
  "I.E ➔ National Airspace System",
  "I.F ➔ Performance and Limitations",
  "I.G ➔ Operation of Systems",
  "I.H ➔ Human Factors",
  "II.A ➔ Preflight Assessment",
  "II.B ➔ Flight Deck Management",
  "II.C ➔ Engine Starting",
  "II.D ➔ Taxiing",
  "II.F ➔ Before Takeoff Check"]),

("OralBring", "What To Bring", "Checkride Day",
 "From the FAA's own checklist in FAA-G-ACS-2, the ACS Companion Guide for Pilots. Split it into what is on YOU, what is in the AIRCRAFT, and what comes out of the maintenance hangar — the examiner asks for all three.",
 ["You ➔ government-issued photo and signature ID",
  "You ➔ your pilot certificate (the student pilot certificate)",
  "You ➔ current medical certificate, or BasicMed qualification where it applies",
  "You ➔ the completed FAA Form 8710-1 or the IACRA application",
  "You ➔ the Airman Knowledge Test Report — and the examiner will test the codes you missed",
  "You ➔ your logbook with every required instructor endorsement",
  "You ➔ a previous Notice of Disapproval or Letter of Discontinuance, if there was one",
  "Aircraft ➔ the ARROW documents: airworthiness certificate, registration, operating limitations, weight and balance",
  "Aircraft ➔ the POH and FAA-approved Airplane Flight Manual",
  "Maintenance ➔ the logbook record of airworthiness inspections and Airworthiness Directive compliance",
  "Money ➔ the examiner's fee, arranged in advance"]),

("OralOutcome", "How The Test Ends", "Pass, Bust or Stop",
 "Three possible endings, and the difference between the last two is the single most confused point in checkride paperwork. 14 CFR 61.43 governs.",
 ["Satisfactory ➔ every Area of Operation passed. 61.43(c): fail ANY Area of Operation and you fail the test",
  "Notice of Disapproval ➔ FAA Form 8060-5, issued when YOUR performance was unsatisfactory. It lists the Tasks failed and those not completed",
  "Letter of Discontinuance ➔ issued when the test stops for any reason OTHER than your performance — weather, an aircraft snag, running out of daylight",
  "Either way ➔ you keep credit for the Areas of Operation you already passed",
  "The clock ➔ 61.43(f): pass the remainder within 60 days of the date the test was discontinued, or you start over",
  "Bring it back ➔ the original disapproval or discontinuance form, any additional training endorsement, and a new signed application",
  "The catch ➔ a Letter of Discontinuance does NOT extend the expiry of your knowledge test report",
  "The other catch ➔ if the examiner doubts your competence in an area you were credited with, they may re-examine it anyway. Credit is not a right"]),

("OralHypoxia", "The Four Hypoxias", "Aeromedical",
 "Four types, four places in the chain where oxygen delivery breaks. Lungs, blood, pump, cell. The pair examiners catch people on is carbon monoxide versus alcohol — they are NOT the same type. Note the taxonomy is from the PHAK and AC 61-107B, not from the AIM.",
 ["Hypoxic ➔ at the LUNGS — not enough oxygen pressure to get in. The altitude one, and the most common in aviation",
  "Hypemic ➔ in the BLOOD — it cannot carry what it took in. Carbon monoxide, anaemia, bleeding, smoking",
  "Stagnant ➔ the PUMP — blood is not circulating. Heart failure, shock, excessive G, cold",
  "Histotoxic ➔ at the CELL — the oxygen arrives but cannot be used. ALCOHOL and narcotics",
  "Why CO is hypemic ➔ haemoglobin bonds with carbon monoxide about 200 times more readily than with oxygen",
  "First symptoms ➔ euphoria and a carefree feeling — you feel fine, which is the danger",
  "Then ➔ headache, drowsiness, dizziness, tingling, slowed reaction, impaired judgement, tunnel vision, cyanosis",
  "Required oxygen (91.211) ➔ 12,500 to 14,000 MSL crew beyond 30 minutes; above 14,000 crew at all times; above 15,000 every occupant PROVIDED",
  "Recommended oxygen ➔ above 10,000 ft by day and above 5,000 ft at night. Not a regulation",
  "Night vision ➔ starts degrading as low as 5,000 ft cabin altitude"]),

("OralIllusions", "Spatial Disorientation", "Aeromedical",
 "The vestibular illusions come from the inner ear losing the plot; the visual ones come from the eye being fooled on approach. The gradeable half is not the name — it is what each one makes you DO. Nearly every approach illusion drives you LOW; the exceptions are a wide runway, downsloping terrain, fog and bright approach lighting.",
 ["The leans ➔ a bank entered too slowly to be sensed, then corrected abruptly. Makes you roll back into the original bank",
  "Coriolis ➔ an abrupt head movement in a prolonged constant-rate turn. Makes you manoeuvre violently to stop a rotation that is not happening",
  "Graveyard spiral ➔ losing altitude in a long coordinated turn. Makes you pull back, tightening the spiral",
  "Somatogravic ➔ rapid acceleration feels like a pitch up. Makes you push into a dive. Deceleration does the reverse",
  "Inversion ➔ abrupt level-off from a climb feels like tumbling backwards. Makes you push abruptly nose low",
  "Elevator ➔ an updraft feels like a pitch up. Makes you push nose low. A downdraft does the reverse",
  "False horizon ➔ sloping cloud, an obscured horizon, ground lights mistaken for stars. Puts you in a dangerous attitude",
  "Autokinesis ➔ stare at a single light in the dark and it appears to move. Makes you chase it",
  "Narrow runway ➔ you feel HIGH, so you fly LOW and risk landing short. A wide runway does the reverse",
  "Upsloping runway or terrain ➔ you feel HIGH, so you fly LOW. Downsloping does the reverse",
  "Black hole or featureless terrain ➔ water, snow or darkness with no cues. You feel high and fly LOW",
  "Rain on the windscreen ➔ refraction makes you feel high, so you fly LOW. Haze does the same",
  "Fog ➔ the odd one out — penetrating fog feels like a pitch up, so you steepen the approach abruptly",
  "Bright runway and approach lighting ➔ makes the runway feel CLOSER, so you fly HIGH. Dim lighting does the reverse"]),

("OralAttitudes", "Hazardous Attitudes", "Know These Verbatim",
 "Five attitudes, five antidotes, and the examiner expects the antidote word for word. The drill is recognise the thought, label it, recite the antidote.",
 ["Anti-authority (Don't tell me) ➔ Follow the rules. They are usually right.",
  "Impulsivity (Do it quickly) ➔ Not so fast. Think first.",
  "Invulnerability (It won't happen to me) ➔ It could happen to me.",
  "Macho (I can do it) ➔ Taking chances is foolish.",
  "Resignation (What's the use?) ➔ I'm not helpless. I can make a difference.",
  "DECIDE ➔ Detect, Estimate, Choose, Identify, Do, Evaluate — and it loops",
  "3P ➔ Perceive the hazards, Process the risk, Perform the action",
  "Perceive uses ➔ PAVE",
  "Process uses ➔ CARE: Consequences, Alternatives, Reality, External pressures",
  "Perform uses ➔ TEAM: Transfer, Eliminate, Accept, Mitigate"]),
]

# ---------------------------------------------------------------- mcq banks
PREREQ = [
("Your knowledge test was passed on 14 March 2025. Through when is it valid for the practical test?",
 ["31 March 2027 — 24 calendar months preceding the MONTH you complete the practical test.",
  "14 March 2027, exactly 24 months to the day.",
  "31 December 2026, the end of the second calendar year."],
 "61.39(a)(1)(i) counts calendar months preceding the MONTH of the practical test, so a test passed any day in March 2025 lives until the last day of March 2027. Counting to the anniversary date throws away most of a month you are legally entitled to — and in the other direction, assuming a rolling 24 months from the exact date can put you a day over."),

("The 61.39(a)(6) endorsement from your instructor certifies three things. Which is NOT one of them?",
 ["That you have completed all the aeronautical experience in 61.109.",
  "That you received training within the 2 calendar months preceding the month of application.",
  "That you have demonstrated satisfactory knowledge of the subjects you were deficient on in the knowledge test."],
 "The experience requirement is its own item, 61.39(a)(3) — the endorsement does not certify it. What (a)(6) certifies is: training received and logged within 2 calendar months preceding the month of application, that you are prepared for the test, and that you have been remediated on your missed knowledge-test subjects. That last clause is the mechanism that feeds your missed codes straight into the oral."),

("How much total flight time does 61.109(a) require for an airplane single-engine land private pilot certificate?",
 ["40 hours, including 20 hours of flight training and 10 hours of solo flight training.",
  "35 hours, including 20 dual and 10 solo.",
  "40 hours, including 30 dual and 10 solo."],
 "40 hours total under Part 61, of which 20 are with an instructor and 10 are solo. The 35-hour figure is real but belongs elsewhere: an approved Part 141 course (Appendix B) or an approved course at a Part 142 training centre under 61.109(k)(3). The total and the dual/solo split are separate requirements and both must be met."),

("What does 61.109(a)(5)(ii) require of the long solo cross-country?",
 ["150 NM total distance, full-stop landings at three points, and one leg with a straight-line distance of more than 50 NM.",
  "100 NM total distance with a full-stop landing at two points.",
  "150 NM total distance with a full-stop landing at a towered airport."],
 "Three numbers in one requirement: 150 NM total, three points with full-stop landings, and at least one straight-line segment over 50 NM. The towered-airport requirement is a DIFFERENT paragraph — (a)(5)(iii), three takeoffs and landings to a full stop at an airport with an operating control tower. Merging the two is the standard error."),

("The night training in 61.109(a)(2) requires a cross-country of what distance, and landings where?",
 ["One cross-country of over 100 NM total distance, plus 10 takeoffs and landings to a full stop at an airport.",
  "One cross-country of over 150 NM, plus 10 takeoffs and landings at a towered airport.",
  "One cross-country of over 100 NM, plus 3 takeoffs and landings to a full stop."],
 "Over 100 NM total for the night cross-country, and 10 full-stop takeoffs and landings, each involving a flight in the traffic pattern. Note the airport does NOT have to be towered for the night ten — that requirement attaches only to the three SOLO landings in (a)(5)(iii). And each landing must involve a pattern, so a string of full-stops without re-entering does not count."),

("What is the minimum age and the certificate you must already hold to be issued a private pilot certificate?",
 ["17 years old for an airplane rating, and you must hold a student, sport or recreational pilot certificate.",
  "16 years old, and you must hold a student pilot certificate.",
  "17 years old, with no requirement to hold any prior certificate."],
 "61.103(a) sets 17 for anything other than a glider or balloon, which are 16 under (b). 61.103(j) requires you to already hold a US student, sport or recreational pilot certificate — you upgrade to private, you do not start from nothing. 16 is the minimum age to fly SOLO as a student, which is the figure that gets substituted here."),

("Which best describes what the examiner must cover in the Plan of Action?",
 ["At least one Knowledge and one Risk Management element per Task, ALL Skill elements, and every subject you missed on the knowledge test.",
  "Every Knowledge, Risk Management and Skill element in the ACS.",
  "Whichever elements the examiner chooses on the day, with no minimum."],
 "One K, one R, all S, plus your missed knowledge-test codes. That is a FLOOR, not a ceiling — the examiner may add elements at discretion, and some Tasks carry their own sampling notes. Two practical consequences: your Airman Knowledge Test Report is a guaranteed question list, and you cannot predict the rest, so you prepare the whole Task."),

("The weather turns and the examiner stops the test after you have passed the oral. What paperwork do you get?",
 ["A Letter of Discontinuance — the test stopped for a reason other than your performance.",
  "A Notice of Disapproval, FAA Form 8060-5.",
  "Nothing — the test simply resumes another day with no paperwork."],
 "Discontinuance is for weather, an aircraft problem, daylight, anything that is not you. A Notice of Disapproval means your performance was unsatisfactory. Both preserve credit for what you passed, but they are different documents saying different things about you, and a DPE will expect you to know which is which."),

("How long do you have to complete the remaining Areas of Operation after a test is discontinued?",
 ["60 days from the date the practical test was discontinued.",
  "60 days from the date your knowledge test expires.",
  "24 calendar months, the same as the knowledge test."],
 "61.43(f)(1). Note that a Letter of Discontinuance does NOT extend your knowledge test report — if the written expires inside those 60 days, the 60 days do not help you. And the 60 days run from the date the test was DISCONTINUED, not from when you feel ready or when your instructor signs you off again — miss them and the credit is gone and you sit the whole test."),

("What does 14 CFR 61.45 require of the aircraft you bring to the practical test?",
 ["US registry, of the category and class for the rating, with a standard or appropriate special airworthiness certificate, two pilot stations and controls operable by both pilots.",
  "Any aircraft the examiner approves, regardless of registry.",
  "US registry and a current annual inspection — nothing further."],
 "61.45 is specific: category and class (and type, where a rating is required), a standard airworthiness certificate or one in the limited, primary or light-sport category, at least two pilot stations with adequate visibility for each person, no operating limitation that prohibits any required Area of Operation, and engine and flight controls easily reached and operable in a conventional manner by BOTH pilots. An aircraft with limiting characteristics produces a limitation on your certificate."),

("You failed the practical test. What is required before you can retest?",
 ["Additional training from an authorized instructor, plus a logbook or training-record endorsement saying you received it.",
  "A mandatory 30-day waiting period before you may reapply.",
  "Retaking the knowledge test."],
 "Training plus the endorsement, and the instructor completes the Instructor's Recommendation block on the application. There is NO mandatory waiting period at the private pilot level, and the knowledge test stands as long as it is still inside its 24-calendar-month window. Both of those are invented requirements people expect to exist."),

("Which document did the FAA make legally binding at 14 CFR 61.14 for your practical test?",
 ["FAA-S-ACS-6C, the Private Pilot for Airplane Category Airman Certification Standards, November 2023 edition.",
  "FAA-S-ACS-6B, Change 1, the previous edition.",
  "The Private Pilot Practical Test Standards, which the ACS supplements."],
 "61.14 incorporates the specific edition by reference — FAA-S-ACS-6C, November 2023, effective 31 May 2024. It SUPERSEDES 6B Change 1 rather than supplementing it, and it replaced the PTS entirely for this certificate: the ACS is a single document covering the standards for both the knowledge test and the practical test."),

("14 CFR 61.43(a) says the practical test consists of four things. Which is one of them, beyond performing the Tasks to standard?",
 ["Demonstrating sound judgment.",
  "Completing the flight within a set time limit.",
  "Passing a separate oral examination before any flight begins."],
 "61.43(a)(4): demonstrating sound judgment — alongside performing the ACS Tasks, demonstrating mastery of the aircraft, and demonstrating proficiency within the approved standards. There is no time limit and no separately-scored oral; the ground and flight portions are one test, and judgement is graded throughout both."),

("You need the aeronautical experience complete by when?",
 ["Before APPLYING for the practical test.",
  "Before taking the practical test, which can be the same morning.",
  "Within 60 days after the practical test."],
 "61.103(g) says the experience must be met before applying, and 61.39(a)(3) repeats it as a prerequisite. The distinction matters because the application is signed before the test begins — finishing a required hour on the way to the checkride does not fix a shortfall that existed when you signed."),
]

AEROMED = [
("A cracked exhaust manifold lets fumes into the cabin. Which type of hypoxia results?",
 ["Hypemic — the blood cannot carry oxygen because carbon monoxide has taken the haemoglobin.",
  "Histotoxic — the cells cannot use the oxygen delivered.",
  "Stagnant — the blood is not circulating properly."],
 "Carbon monoxide is a BLOOD problem: haemoglobin bonds with it about 200 times more readily than with oxygen, so the blood arrives at the tissues already loaded with the wrong gas. Histotoxic is the ALCOHOL one — the oxygen gets there and the cell cannot use it. Swapping those two is the most common error in this whole subject."),

("You smell nothing unusual but have a headache and feel drowsy with the cabin heat on. What do you do?",
 ["Shut off the cabin heat, open the fresh air vents, and land as soon as practical.",
  "Open the fresh air vents and continue with the heat on to stay warm.",
  "Descend to a lower altitude and continue the flight."],
 "Carbon monoxide is colourless, odourless and tasteless, so you will not smell it. Most light-aircraft heaters work by passing cabin air over the exhaust manifold, so a crack feeds exhaust straight into the cabin — which means the heater must go OFF, not just the vents open. Get fresh air, land, and seek medical attention if symptoms persist."),

("Early hyperventilation and early hypoxia feel much the same. What is the correct action sequence?",
 ["Treat for hypoxia first — 100 percent oxygen and check the system — then consciously slow the breathing.",
  "Slow the breathing first; if that fails, then consider oxygen.",
  "Descend immediately without taking either action."],
 "The AIM is honest that you cannot reliably tell them apart early on, and that they can occur together. So you cover the one that kills faster: oxygen first, verify the system is working, then address rate and depth of breathing. The physical tell if you need one — hyperventilation gives a pale, clammy look with muscle spasms; hypoxia gives cyanosis and limp muscles."),

("You take off at night and feel a strong sensation of pitching up. What is happening and what will it make you do?",
 ["The somatogravic illusion from rapid acceleration — it makes you push into a dive.",
  "The elevator illusion from an updraft — it makes you pull up.",
  "The inversion illusion — it makes you climb steeply."],
 "Acceleration is sensed by the same organ that senses tilt, so it reads as nose-up. The lethal part is the correction: you push, and on a dark night with no horizon you fly into the ground. The elevator illusion comes from a vertical gust, not acceleration; the inversion illusion comes from an abrupt level-off after a climb."),

("You are on approach to a runway that is narrower than the one you usually use. What is the illusion and the danger?",
 ["You feel higher than you are, so you fly a lower approach and risk landing short.",
  "You feel lower than you are, so you fly a higher approach and risk overshooting.",
  "Runway width produces no illusion as long as the runway is lit."],
 "A narrow runway fills less of your view, which your brain reads as being further away and therefore higher. You correct down. A WIDE runway does the opposite and has you levelling off high and landing hard. The same logic runs the slope illusions: upsloping makes you feel high and fly low."),

("Which approach illusion makes you fly a STEEPER approach rather than a lower one?",
 ["Penetrating fog, which produces a sensation of pitching up.",
  "Rain on the windscreen.",
  "Featureless terrain such as water or snow."],
 "Fog is the odd one out. Rain and haze both make you feel high and fly low; a black-hole or featureless approach does the same. Fog gives an illusion of pitching up and the pilot steepens the approach, often abruptly. Learning the pattern — almost everything drives you LOW except a wide runway, downslope, bright approach lighting and fog — is worth more than the individual names."),

("You stare at a single steady light on a dark night and it appears to move. What is this?",
 ["Autokinesis — and trying to align the aircraft with it can lose you control.",
  "The false horizon illusion.",
  "The leans."],
 "Autokinesis takes only a few seconds of fixation. The prevention is the same as the cure: keep the eyes moving and cross-check the light against other references. The false horizon comes from sloping cloud or ground lights mistaken for stars; the leans is a vestibular bank illusion, not a visual one."),

("How long does complete dark adaptation take, and what helps?",
 ["About 30 minutes in total darkness — a moderate degree can be reached in about 20 minutes under dim red cockpit lighting.",
  "About 5 minutes, regardless of lighting.",
  "About 60 minutes, and cockpit lighting colour makes no difference."],
 "30 minutes for full adaptation, roughly 20 under dim red light. A bright light for more than about a second undoes it. Dark adaptation is also impaired above 5,000 ft — which is why the FAA recommends oxygen at night above 5,000 ft even though no regulation requires it until 12,500."),

("Why must you look slightly to the side of an object to see it at night?",
 ["The centre of the retina is all cones, which do not work in low light — the rods that do are in the periphery.",
  "The centre of the retina is all rods, which are slower to respond at night.",
  "Peripheral vision has better colour discrimination at night."],
 "The fovea at the centre is exclusively cones, so at night your sharpest daytime vision becomes a blind spot 5 to 10 degrees wide. Off-centre viewing, looking 5 to 10 degrees to the side, puts the image on the rods. Rods cannot see colour at all, so the third option has it backwards. The scale of it: an aircraft you would see at 5,000 ft by day may not be detected until 500 ft using peripheral vision."),

("What is the FAA's recommended visual scanning technique?",
 ["Short, regularly spaced eye movements of no more than 10 degrees, holding each block for at least 1 second.",
  "A smooth continuous sweep across the whole windscreen.",
  "Scanning only the sector into which the aircraft is turning."],
 "The eye cannot detect anything while it is moving, so a smooth sweep sees nothing — that is why the AIM specifies discrete movements with a pause. The AIM also gives the inside/outside budget: no more than 4 to 5 seconds on the instrument panel for every 16 seconds outside."),

("You went scuba diving with a controlled ascent, and want to fly at 6,500 ft MSL. How long must you wait?",
 ["At least 24 hours — a dive requiring a controlled ascent means 24 hours whatever the flight altitude.",
  "At least 12 hours, because the flight is below 8,000 ft.",
  "No wait is required below 8,000 ft."],
 "The AIM gives 12 hours only for a dive that did NOT require a controlled ascent, and only below 8,000 ft. A decompression-stop dive is 24 hours regardless. And note the threshold is ACTUAL FLIGHT ALTITUDE above mean sea level, not cabin altitude — the AIM says so explicitly, because it accounts for the risk of a decompression in flight."),

("You made a non-decompression dive and want to fly at 9,500 ft MSL. How long must you wait?",
 ["At least 24 hours — above 8,000 ft the wait is 24 hours after any dive.",
  "At least 12 hours, since it was a non-decompression dive.",
  "At least 8 hours."],
 "Above 8,000 ft the dive type stops mattering: 24 hours after ANY dive. This is the half of the rule people drop, because the 12-hour figure is the one that sticks. A normally aspirated single at 9,500 ft is over the line."),

("Your last drink was 9 hours ago and you feel fine, but you have a hangover. May you fly?",
 ["No — 91.17(a)(2) prohibits acting as a crewmember while under the influence, and a hangover means you still are.",
  "Yes — the 8-hour requirement in 91.17(a)(1) has been met.",
  "Yes, provided your blood alcohol is below 0.04."],
 "91.17(a) sets FOUR independent prohibitions: 8 hours since any alcoholic beverage, not under the influence, not using any drug that affects your faculties contrary to safety, and below 0.04 percent. Clearing one does not clear the others. Note 0.04 is half the usual driving limit, and the AIM recommends 12 to 24 hours between bottle and throttle depending on how much you drank."),

("What is the FAA's guidance on flying after taking an over-the-counter medication?",
 ["Wait at least five dosage intervals after the last dose — and never fly after a new medication until at least 48 hours have passed with no side effects.",
  "Wait 8 hours, the same as for alcohol.",
  "Any medication sold without a prescription is approved for flight."],
 "Five dosage intervals: a 4-to-6-hourly medication means about 30 hours, an 8-hourly one about 40, a 12-hourly one about 60. Two traps worth knowing: cetirizine (Zyrtec) is on the FAA's do-not-fly list despite the non-drowsy marketing, and the usual motion-sickness remedies — meclizine and dimenhydrinate — are grounding, so the cure for airsickness is itself disqualifying. Remember too that the CONDITION may disqualify you even when the drug does not."),

("What is the difference between acute and chronic fatigue?",
 ["Acute fatigue is relieved by rest and adequate sleep; chronic fatigue is not, and requires a physician.",
  "Acute fatigue lasts longer than chronic fatigue.",
  "Chronic fatigue is relieved by a good diet and one night of sleep."],
 "Acute fatigue is the normal tiredness of a long day and rest fixes it. Chronic fatigue builds when there is never enough recovery between episodes, is often psychologically rooted, and is NOT relieved by diet, rest or sleep — it needs medical attention. Answering that rest fixes it is right for one and dangerously wrong for the other. Mild hypoxia is itself a cause of fatigue."),

("You hold a valid third class medical but woke up with a bad head cold. What governs?",
 ["61.53 — you may not act as PIC knowing of a medical condition that would make you unable to meet the requirements for your medical certificate.",
  "Nothing — a valid medical certificate is sufficient authority to fly.",
  "91.17, which covers illness as well as alcohol and drugs."],
 "A medical certificate says an examiner found you fit on the day of the exam. 61.53 imposes a duty on EVERY flight for the life of that certificate, and it grounds you with nothing stamped or revoked — you self-ground. IMSAFE is how you run the check. 91.17 is the alcohol and drugs rule, which is related but separate."),

("Why is an ear or sinus block usually a problem on DESCENT rather than on climb?",
 ["On descent the pressure differential pushes the eustachian tube walls shut, so equalising is harder.",
  "On descent the air is colder, which constricts the tube.",
  "It is equally likely on climb and descent."],
 "Climbing, the expanding middle-ear air escapes fairly freely. Descending, you need air to get IN, and the tube tends to be squeezed closed — especially with any congestion from a cold or allergy. The fix is the Valsalva: pinch the nostrils, close the mouth, blow gently. If it will not clear, climb back up and descend more slowly. A maxillary sinus block refers pain to the upper teeth."),

("The FAA's note on treating a sinus block with decongestants contains a trap. What is it?",
 ["Oral decongestants impair pilot performance, so the treatment can itself make you unfit to fly.",
  "Decongestant sprays are prohibited by regulation.",
  "Decongestants must be taken at least 8 hours before flight."],
 "The AIM says sprays give inadequate protection and that oral decongestants impair performance. So the sequence people reach for — feel congested, take something, go fly — is the wrong one. The correct answer to flying with a cold is not to fly with a cold."),

("What is the antidote to the MACHO hazardous attitude?",
 ["Taking chances is foolish.",
  "It could happen to me.",
  "Not so fast. Think first."],
 "Examiners want these word for word. Macho (I can do it) is answered with Taking chances is foolish. It could happen to me answers INVULNERABILITY; Not so fast, think first answers IMPULSIVITY. The other two: Anti-authority (Don't tell me) is Follow the rules, they are usually right; Resignation (What's the use?) is I'm not helpless, I can make a difference."),

("In the 3P model, which checklist supports the PERCEIVE step?",
 ["PAVE — Pilot, Aircraft, enVironment, External pressures.",
  "CARE — Consequences, Alternatives, Reality, External pressures.",
  "TEAM — Transfer, Eliminate, Accept, Mitigate."],
 "Perceive the hazards with PAVE, Process the risk with CARE, Perform the action with TEAM. Each P has its own checklist and the model loops continuously. This mapping is the clean answer to the examiner's question about where PAVE fits in ADM, and it is worth having on the tip of your tongue."),

("Which correctly gives the DECIDE model?",
 ["Detect, Estimate, Choose, Identify, Do, Evaluate.",
  "Determine, Evaluate, Consider, Implement, Decide, Execute.",
  "Detect, Evaluate, Choose, Implement, Decide, Execute."],
 "Detect the change, Estimate the need to react, Choose a desirable outcome, Identify the actions, Do them, Evaluate the effect — and the last step feeds back into the first. The other two options are plausible-sounding inventions, which is exactly how this is tested: you either know the six words or you guess."),

("At what altitude does 91.211 require EVERY OCCUPANT to be provided with supplemental oxygen?",
 ["Above 15,000 feet MSL cabin pressure altitude.",
  "Above 14,000 feet MSL.",
  "Above 12,500 feet MSL."],
 "Three tiers and the top one is the only one that reaches the passengers: above 12,500 up to and including 14,000 the required crew uses it beyond 30 minutes; above 14,000 the crew uses it at all times; above 15,000 every occupant must be PROVIDED with it. Provided, not required to use — the passenger is not compelled to put it on."),

("Judgement, memory and the ability to make calculations become impaired at roughly what cabin altitude in a normal healthy pilot?",
 ["Between 12,000 and 15,000 feet.",
  "Between 5,000 and 8,000 feet.",
  "Above 20,000 feet only."],
 "The AIM says significant altitude hypoxia usually does not occur in a healthy pilot below 12,000 ft, and that between 12,000 and 15,000 judgement, memory, alertness, coordination and calculation are impaired. Performance seriously deteriorates within 15 minutes at 15,000. NIGHT VISION is the exception that starts much lower, from about 5,000 ft."),

("What is empty-field myopia and when does it occur?",
 ["In a featureless sky the eyes relax to an intermediate focus of about 10 to 30 feet, so you look without seeing.",
  "A permanent short-sightedness caused by repeated high-altitude flight.",
  "The inability to focus on the instrument panel after looking outside."],
 "With nothing to focus on, the eye defaults to a near-intermediate distance and traffic simply does not register. The countermeasure is to give the eye something real: focus periodically on a distant object, even a dim one. It pairs with the scanning technique — a moving eye with something to land on sees traffic; a relaxed stare into haze does not."),

("A pilot under chronic stress that exceeds their ability to cope should:",
 ["Not exercise airman privileges, and consult a physician.",
  "Fly only short local flights in good weather until it passes.",
  "Continue flying, since flying is a recognised stress reliever."],
 "The FAA is unambiguous that chronic stress causes performance to fall sharply and that such pilots are not safe and should not exercise their privileges. Acute stress is different — a healthy person copes with a discrete threat, and that is the fight-or-flight response doing its job. It becomes chronic when it never lets up."),
]

INOP = [
("The landing light burns out. There is no MEL for the aircraft. You want to fly a day VFR local flight. What is the procedure?",
 ["Run 91.213(d): confirm it is not part of the VFR-day type certificate, not required by 91.205 for this flight, not required by an AD and not on the equipment list, then deactivate or remove it and placard it INOPERATIVE.",
  "The aircraft is unairworthy and may not be flown until it is repaired.",
  "Note it in the aircraft records and fly — inoperative equipment needs no further action."],
 "91.213(d) is the procedure for flying legally without an MEL, and it is four filters plus two actions plus a determination. A landing light passes all four for a private day VFR flight — 91.205(c)(4) only requires one if the aircraft is operated for hire. Deactivate or remove, placard INOPERATIVE, and either you or a mechanic determines it is not a hazard."),

("What is the difference between an MEL and a KOEL?",
 ["An MEL is an FAA-approved document specific to that aircraft and operator; a KOEL is a list in the POH showing what equipment is required for each kind of operation.",
  "They are two names for the same list.",
  "An MEL applies to day VFR only; a KOEL applies to night."],
 "The MEL is approved and becomes a supplemental type certificate — once you have one, you use it and 91.213(d) no longer applies. The Kinds of Operation Equipment List lives in the POH and tells you what must work for day VFR, night VFR and so on. Most training aircraft have a KOEL and no MEL, which is why 91.213(d) is the path you actually use."),

("The examiner hands you the maintenance records and asks you to prove the aircraft is airworthy. What are you tracing?",
 ["The Annual, the 100-hour if it applies, the transponder and altimeter checks, the ELT, and compliance with every applicable Airworthiness Directive.",
  "Only the Annual inspection and the registration expiry date.",
  "The hours flown since the last oil change."],
 "ACS Task I.B Skill element S2 is literally determine the airplane is airworthy in the scenario given by the evaluator — from the books, not from memory. Dates and tach times, and the AD list is the part students forget. Two things make an aircraft airworthy: it conforms to its type certificate, and it is in condition for safe operation."),

("Who is responsible for determining the aircraft is airworthy before flight?",
 ["The pilot in command, under 91.7 — regardless of the owner's separate responsibility under 91.403.",
  "The owner or operator alone, under 91.403.",
  "The mechanic who signed the last inspection."],
 "Both are true at once and the examiner wants both. 91.403 puts primary responsibility for MAINTAINING airworthiness on the owner or operator. 91.7(b) makes the PIC responsible for determining whether the aircraft is in condition for safe flight, and for discontinuing the flight when an unairworthy condition occurs. You cannot point at the owner after the fact."),

("What is a special flight permit and what is it for?",
 ["A ferry permit issued under 14 CFR 21.197 allowing an aircraft that does not currently meet airworthiness requirements to be flown to a place where repairs can be made.",
  "A permit allowing flight with inoperative equipment indefinitely.",
  "A permit required to fly an aircraft with a special airworthiness certificate."],
 "21.197 — the aircraft is capable of safe flight but does not meet applicable airworthiness requirements, so the FAA issues a permit for a specific purpose and route. Flying an aircraft out of annual to the maintenance base is the classic case. It is not a workaround for inoperative equipment on a normal flight, and it has nothing to do with special airworthiness certificates."),

("What makes an Airworthiness Directive different from a Service Bulletin?",
 ["An AD is a regulation issued under Part 39 and compliance is mandatory; a service bulletin is the manufacturer's recommendation.",
  "Both are mandatory, but ADs are issued by the manufacturer.",
  "An AD applies only to commercial operators."],
 "Part 39 makes an AD a legally binding rule addressing an unsafe condition. A manufacturer's service bulletin is advice unless an AD adopts it. ADs can be one-time or recurring, emergency or routine, and the aircraft records must show compliance with every one that applies — which is why the AD list is part of proving airworthiness."),

("Which is true of a standard airworthiness certificate?",
 ["It has no expiry date and remains valid as long as the aircraft is maintained in accordance with Parts 43 and 91.",
  "It expires every 7 years and must be renewed.",
  "It expires every 12 calendar months with the annual inspection."],
 "The airworthiness certificate is the ARROW item that does NOT expire, provided the maintenance keeps up. The 7-year figure belongs to the REGISTRATION under 47.40; the 12 calendar months belongs to the annual INSPECTION under 91.409. Three different documents, three different behaviours, and the question is which one you were asked about."),

("Where must the airworthiness certificate be carried in the aircraft?",
 ["Displayed at the cabin or cockpit entrance where it is legible to passengers or crew.",
  "In the glove box with the other required documents.",
  "With the aircraft maintenance records, which may be kept at the operator's base."],
 "91.203(b) requires it to be DISPLAYED and legible — it is the only ARROW item with a placement requirement. The registration must be aboard but need not be displayed, and the maintenance records are specifically NOT required to be carried in the aircraft. The examiner will expect you to point at it."),

("Your aircraft is used for flight instruction provided by the operator. Which inspection applies that would not apply to a privately owned aircraft?",
 ["The 100-hour inspection under 91.409(b).",
  "The annual inspection under 91.409(a).",
  "The transponder check under 91.413."],
 "The 100-hour attaches to the OPERATION: carrying persons for hire, or flight instruction for hire in an aircraft provided by the person giving the instruction — which describes a school aircraft exactly. The annual applies to every aircraft, and the transponder check applies to any use of the transponder. Only the 100-hour is triggered by what the aircraft is being used FOR."),

("The 100-hour is due in 6 hours and the maintenance base is a 90-minute flight away. What does 91.409(b) allow?",
 ["You may exceed the 100 hours by up to 10 hours while EN ROUTE to the inspection, and the excess counts against the next interval.",
  "You may exceed it by 10 hours for any purpose.",
  "You may not exceed it under any circumstances."],
 "The 10 hours is a ferry allowance, not a grace period — it applies only while flying to where the inspection can be done, and the overrun is subtracted from the next 100. Treating it as 110 hours of normal flying is the misreading the rule is written to prevent."),

("A required instrument fails in flight. What does 91.7 require of you?",
 ["Discontinue the flight when an unairworthy condition occurs.",
  "Continue to the destination and report it on landing.",
  "Nothing — 91.7 applies only before flight."],
 "91.7(b) covers both ends: the PIC determines the aircraft is in condition for safe flight BEFORE flight, and shall discontinue the flight when an unairworthy condition occurs. Discontinue does not mean land immediately in a field — it means end the flight at a suitable place as soon as practical rather than pressing on."),

("What two things must be true for an aircraft to be airworthy?",
 ["It conforms to its type certificate, and it is in condition for safe operation.",
  "It has a current annual, and the registration has not expired.",
  "It has passed all inspections, and the pilot is current."],
 "Conformity plus condition. Inspections and paperwork are how you EVIDENCE those two things, not the definition itself. The pilot's currency is a Part 61 matter and has nothing to do with whether the aircraft is airworthy — merging the two is a category error an examiner will notice."),

("After you perform preventive maintenance, what must the record entry contain?",
 ["A description of the work, the date of completion, and your name, signature and certificate number.",
  "Only the date and your initials.",
  "Nothing — pilot-performed preventive maintenance requires no entry."],
 "43.9. It goes in the AIRCRAFT maintenance records, not your flight logbook, and the certificate number is the part people leave out. The work itself must also be on the closed list in Part 43 Appendix A paragraph (c), and it must not involve complex assembly operations."),

("The examiner asks what you would do about a cracked navigation light lens discovered on preflight, at night. What is the reasoning?",
 ["Position lights are required for night flight under 91.205(c), so the aircraft cannot legally be flown at night until it is fixed.",
  "Placard it inoperative and fly — a lens is cosmetic.",
  "Fly, provided the bulb still illuminates."],
 "91.213(d) fails at the second filter: the item IS required by 91.205 for this kind of flight, so the deactivate-and-placard path is not available to you. And 91.209 requires position lights to be displayed from sunset to sunrise. The same aircraft could legally fly the identical route by day — which is the point of the scenario."),
]

XC = [
("What are the three types of preflight weather briefing, and when do you ask for each?",
 ["Standard for a complete picture, Abbreviated to update or supplement, Outlook when departure is 6 or more hours away.",
  "Standard, Detailed and Emergency.",
  "Full, Partial and Telephone."],
 "Ask for the OUTLOOK first if you are planning ahead — it is explicitly for a departure 6 or more hours out and does not include current conditions in the way a standard does. Then a STANDARD before you go, and an ABBREVIATED to top it up. Saying you always want a standard briefing is not wrong, but the examiner is checking you know why the other two exist."),

("Is a VFR flight plan required, and what does filing one actually get you?",
 ["Not required — it buys you search and rescue, and nothing else.",
  "Required for any flight beyond 50 NM from the departure airport.",
  "Required whenever you will enter Class E airspace."],
 "A VFR flight plan is purely voluntary and provides no ATC service of any kind — it does not open a radar flight-following service and it does not give you a clearance. What it does is start a search if you fail to close it. Which is the other half of the answer: you must CLOSE it, because nobody else will."),

("You are lost. What is the sequence?",
 ["Climb, Communicate, Confess, Comply, Conserve.",
  "Confess, Climb, Comply, Communicate, Conserve.",
  "Communicate, Conserve, Climb, Confess, Comply."],
 "The five Cs, and the order is the point. CLIMB first — it buys radio and radar range, better visibility and more gliding options. Then communicate, confess that you are lost rather than dressing it up, comply with what you are given, and conserve fuel throughout. Confessing first from low altitude where nobody can hear you is the wrong order."),

("Weather ahead is deteriorating and you decide to divert. What do you do first?",
 ["Turn toward the alternate immediately, then work out the heading, time and fuel.",
  "Complete a full navigation log to the alternate before changing heading.",
  "Continue on course while you contact Flight Service for advice."],
 "Turn first, compute second. Every minute spent head-down with a plotter is a minute flying deeper into the weather you decided to leave. Estimate the heading by eye off the chart, start the turn and the clock, then refine. The ACS is testing your decision-making here more than your arithmetic."),

("What does the Maximum Elevation Figure in a sectional quadrangle represent?",
 ["The highest terrain or obstacle elevation in that quadrangle, in thousands and hundreds of feet MSL.",
  "The minimum safe altitude you must fly in that quadrangle.",
  "The height of the highest obstacle above ground level."],
 "The MEF is a DATUM, not a minimum altitude — it tells you what the highest thing is, and it already includes an allowance for obstacles of unknown height. You then add your own margin on top. Reading it as a legal minimum, or as an AGL figure, are the two misreadings."),

("An obstacle on the chart shows 2,049 with (1,150) beneath it. What do the two numbers mean?",
 ["2,049 is the top of the obstacle in feet MSL; 1,150 is its height above the ground.",
  "2,049 is its height above ground; 1,150 is its elevation MSL.",
  "2,049 is the terrain elevation; 1,150 is the obstacle height."],
 "Bold number on top is MSL, the parenthesised number beneath is AGL. Your altimeter reads MSL, so the MSL figure is the one your clearance arithmetic starts from — the AGL number is for spotting it out of the window. Starting a 91.119 calculation from the AGL figure gives an answer that looks plausible and is 900 feet low here."),

("How do you convert a true course measured off the chart into a compass heading?",
 ["Apply wind correction to get true heading, then variation to get magnetic heading, then deviation to get compass heading.",
  "Apply variation first, then wind correction, then deviation.",
  "Apply deviation, then variation, then wind correction."],
 "True course, wind correction angle, true heading, variation, magnetic heading, deviation, compass heading. East is least and west is best when applying variation from true to magnetic. Deviation comes last because it is a property of that specific aircraft's compass and comes off the correction card on the panel."),

("Class E airspace begins at 700 ft AGL where the sectional shows what?",
 ["The soft magenta vignette, with the shaded edge facing the airspace.",
  "The soft blue vignette.",
  "A dashed magenta line."],
 "Magenta vignette means the Class E floor is at 700 AGL; a blue vignette means it starts at 1,200. A DASHED magenta line is something different again — Class E extending down to the SURFACE, which is what makes Special VFR available there. Three magenta markings, three different meanings."),

("How much fuel must you have on board for a day VFR cross-country?",
 ["Enough to fly to the first point of intended landing plus 30 minutes at normal cruising speed.",
  "Enough to fly to the destination plus 30 minutes at best-endurance speed.",
  "Enough to fly to the destination plus an alternate."],
 "91.151: destination plus 30 minutes by day, plus 45 at night, and the reserve is computed at NORMAL CRUISING speed, not at the most economical setting you could theoretically fly. There is no VFR alternate requirement — that is an IFR concept that migrates into this answer."),

("What is the significance of a magenta segmented circle around a small airport symbol?",
 ["Class E airspace extending to the surface, which is where Special VFR can be requested.",
  "Class D airspace with a part-time tower.",
  "A restricted area boundary."],
 "The dashed magenta ring is Class E to the surface, and it exists at airports with weather reporting and instrument procedures. Class D is a dashed BLUE ring. The operational consequence is Special VFR: it is only available in the surface area of controlled airspace, so the ring tells you where you could ask for it."),

("You plan to land at an airport with a part-time control tower, arriving after it closes. What changes?",
 ["The airspace reverts to Class E or Class G depending on what is charted, and you use CTAF self-announce procedures.",
  "The airspace always becomes Class G and no radio calls are needed.",
  "The airspace remains Class D and you must still establish two-way communication."],
 "Check the chart supplement — most such fields become Class E, some become Class G, and the weather minimums you must meet change with it. Assuming Class G is the dangerous default because it is the most permissive. Either way the tower frequency usually becomes the CTAF."),

("What do you need to check about your charts before the flight?",
 ["That they are current — an out-of-date sectional may show airspace, frequencies and obstacles that have since changed.",
  "Nothing — VFR charts have no expiry.",
  "Only that the scale is correct for the distance being flown."],
 "Sectionals are issued on a defined cycle and the airspace, frequencies, obstacles and even airport status change between editions. 91.103 requires you to become familiar with all available information concerning the flight, and planning from a superseded chart is the clearest way to fail that. The examiner will look at the date on yours."),

("Where do you find the traffic pattern altitude and the runway lengths for an unfamiliar airport?",
 ["The Chart Supplement.",
  "The sectional chart legend.",
  "The POH performance section."],
 "The Chart Supplement — the old Airport/Facility Directory — carries pattern altitude, runway dimensions and surface, lighting, frequencies, services, and remarks such as noise procedures or obstructions. The sectional gives you the airport's existence, elevation and longest runway at a glance; the detail is in the supplement."),

("What does 91.103 require you to become familiar with for a cross-country flight?",
 ["All available information concerning that flight — including weather, fuel, alternatives, known delays, runway lengths and takeoff and landing distances.",
  "Only the weather and the fuel required.",
  "Only the runway lengths at the airports of intended use."],
 "NWKRAFT covers it: NOTAMs, Weather, Known ATC delays, Runway lengths, Alternates, Fuel, Takeoff and landing data. Note the rule has two tiers — runway lengths and takeoff/landing distance data are required for EVERY flight, while the weather, fuel, alternatives and delays items attach to a flight not in the vicinity of an airport."),

("You want VFR flight following. What is true about it?",
 ["It is a workload-permitting service, and it does not relieve you of see-and-avoid responsibility.",
  "It guarantees separation from all other traffic.",
  "It is the same thing as filing a VFR flight plan."],
 "Flight following gives you traffic advisories when the controller has capacity, and it can be terminated when the workload rises. You remain responsible for seeing and avoiding, and for your own terrain and airspace clearance. It is also entirely separate from a VFR flight plan — one is an ATC service, the other is a search-and-rescue record, and having one does not give you the other."),

("On a cross-country you realise you will arrive after dark. What must you check?",
 ["Your night currency under 61.57(b) if passengers are aboard, the required equipment under 91.205(c), and position lights from sunset to sunrise.",
  "Only that you hold a night rating.",
  "Nothing — a private pilot certificate covers night flight without further conditions."],
 "Three separate clocks. Position lights come on at SUNSET. Passenger night currency runs from one hour after sunset to one hour before sunrise and needs 3 full-stop landings in the preceding 90 days. Logging night time uses civil twilight. And FLAPS equipment must be aboard. There is no such thing as a separate US night rating, which is what the second option invents."),
]

BANKS = [
    ("OralPrereq", "Eligibility & Prerequisites", PREREQ,
     [("Private pilot eligibility and experience", "https://www.youtube.com/results?search_query=61.103+61.109+private+pilot+eligibility+aeronautical+experience+explained"),
      ("What to expect on the checkride", "https://www.youtube.com/results?search_query=private+pilot+checkride+oral+exam+what+to+expect+DPE"),
      ("Understanding the ACS", "https://www.youtube.com/results?search_query=airman+certification+standards+ACS+explained+private+pilot")]),
    ("OralAeromed", "Aeromedical & Human Factors", AEROMED,
     [("Hypoxia and the four types", "https://www.youtube.com/results?search_query=four+types+of+hypoxia+explained+pilot+hypoxic+hypemic+stagnant+histotoxic"),
      ("Spatial disorientation and illusions", "https://www.youtube.com/results?search_query=spatial+disorientation+vestibular+visual+illusions+pilot+explained"),
      ("Night vision and the eye", "https://www.youtube.com/results?search_query=pilot+night+vision+rods+cones+off+center+scanning+explained"),
      ("Hazardous attitudes and ADM", "https://www.youtube.com/results?search_query=five+hazardous+attitudes+antidotes+aeronautical+decision+making")]),
    ("OralInop", "Airworthiness & Inoperative Equipment", INOP,
     [("91.213 inoperative equipment", "https://www.youtube.com/results?search_query=91.213+inoperative+equipment+MEL+KOEL+placard+explained"),
      ("Proving airworthiness from the logbooks", "https://www.youtube.com/results?search_query=prove+aircraft+airworthy+maintenance+logbooks+checkride+oral"),
      ("Airworthiness Directives", "https://www.youtube.com/results?search_query=airworthiness+directives+part+39+compliance+explained+pilot")]),
    ("OralXC", "Cross-Country Planning", XC,
     [("Cross-country flight planning", "https://www.youtube.com/results?search_query=VFR+cross+country+flight+planning+navigation+log+explained"),
      ("Reading a sectional chart", "https://www.youtube.com/results?search_query=how+to+read+a+sectional+chart+MEF+obstacles+airspace+explained"),
      ("Diversion and lost procedures", "https://www.youtube.com/results?search_query=diversion+lost+procedures+five+Cs+private+pilot")]),
]

SPEC = [
    ("The Checkride", ["OralACS", "OralAreas", "OralBring", "OralOutcome", "OralPrereq"]),
    ("Human Factors", ["OralHypoxia", "OralIllusions", "OralAttitudes", "OralAeromed"]),
    ("Airworthiness", ["OralInop"]),
    ("Cross-Country", ["OralXC"]),
]
